-- KOMMS_ADM.IF_APM_LOG definition

-- Drop table

-- DROP TABLE IF_APM_LOG;

CREATE TABLE IF_APM_LOG (
	INFO_SYS_CODE VARCHAR(5) NOT NULL,
	SCRIN_ID VARCHAR(15),
	SCRIN_SKLL_CODE VARCHAR(5),
	EMPLYR_ID VARCHAR(50),
	EMPLYR_IP VARCHAR(20),
	SERVER_IP VARCHAR(20),
	CALL_URL VARCHAR(200),
	CRTN_TM DATE DEFAULT SYSDATE NOT NULL,
	CLNT_RSPNS_TIME NUMBER,
	NTWRK_RSPNS_TIME NUMBER,
	APLCTN_RSPNS_TIME NUMBER,
	FLAG CHAR(1)
);


-- KOMMS_ADM.MAILQUEUE definition

-- Drop table

-- DROP TABLE MAILQUEUE;

CREATE TABLE MAILQUEUE (
	MID NUMBER(9,0) NOT NULL,
	SNAME VARCHAR(50) NOT NULL,
	SMAIL VARCHAR(100) NOT NULL,
	SID VARCHAR(20) NOT NULL,
	SPOS VARCHAR(1),
	RPOS NUMBER(1,0),
	CTNSPOS NUMBER(1,0),
	CONTENTS VARCHAR(1000),
	SDATE DATE,
	SUBJECT VARCHAR(200),
	STATUS NUMBER(1,0),
	CTID NUMBER(1,0),
	CONSTRAINT PK_MAILQUEUE PRIMARY KEY (MID)
);


-- KOMMS_ADM.PMS03FB definition

-- Drop table

-- DROP TABLE PMS03FB;

CREATE TABLE PMS03FB (
	PM03F_PLNT CHAR(2) NOT NULL,
	PM03F_MODL CHAR(4) NOT NULL,
	PM03F_USEE CHAR(1) NOT NULL,
	PM03F_PACK CHAR(4) NOT NULL,
	PM03F_REGN CHAR(1) NOT NULL,
	PM03F_SERL CHAR(3) NOT NULL,
	PM03F_DIST CHAR(5) NOT NULL,
	PM03F_TEAM CHAR(2) NOT NULL,
	PM03F_EXTC CHAR(3) NOT NULL,
	PM03F_INTC CHAR(3) NOT NULL,
	PM03F_BMDL CHAR(12),
	PM03F_OCNN CHAR(4),
	PM03F_VERS CHAR(3),
	PM03F_DEST CHAR(5),
	PM03F_LCNO CHAR(15),
	PM03F_CMPT CHAR(1),
	PM03F_EXPQ NUMBER(5,0) DEFAULT 0,
	PM03F_ORDQ NUMBER(5,0) DEFAULT 0,
	PM03F_CONQ NUMBER(5,0) DEFAULT 0,
	PM03F_FORQ NUMBER(5,0) DEFAULT 0,
	PM03F_MITQ NUMBER(5,0) DEFAULT 0,
	PM03F_PT00 NUMBER(5,0) DEFAULT 0,
	PM03F_PT01 NUMBER(5,0) DEFAULT 0,
	PM03F_PT02 NUMBER(5,0) DEFAULT 0,
	PM03F_PT03 NUMBER(5,0) DEFAULT 0,
	PM03F_PT04 NUMBER(5,0) DEFAULT 0,
	PM03F_PT05 NUMBER(5,0) DEFAULT 0,
	PM03F_PT06 NUMBER(5,0) DEFAULT 0,
	PM03F_PT07 NUMBER(5,0) DEFAULT 0,
	PM03F_PT08 NUMBER(5,0) DEFAULT 0,
	PM03F_PT09 NUMBER(5,0) DEFAULT 0,
	PM03F_PT10 NUMBER(5,0) DEFAULT 0,
	PM03F_PT11 NUMBER(5,0) DEFAULT 0,
	PM03F_BDYQ NUMBER(5,0) DEFAULT 0,
	PM03F_TRMQ NUMBER(5,0) DEFAULT 0,
	PM03F_PRDQ NUMBER(5,0) DEFAULT 0,
	PM03F_SHPQ NUMBER(5,0) DEFAULT 0,
	PM03F_LCGU CHAR(1) DEFAULT ' ',
	PM03F_STAT CHAR(1) DEFAULT ' ',
	PM03F_CD01 CHAR(4) DEFAULT ' ',
	PM03F_CD02 CHAR(4) DEFAULT ' ',
	PM03F_CD03 CHAR(4) DEFAULT ' ',
	PM03F_CD04 CHAR(4) DEFAULT ' ',
	PM03F_CD05 CHAR(4) DEFAULT ' ',
	PM03F_CD06 CHAR(4) DEFAULT ' ',
	PM03F_CD07 CHAR(4) DEFAULT ' ',
	PM03F_CD08 CHAR(4) DEFAULT ' ',
	PM03F_CD09 CHAR(4) DEFAULT ' ',
	PM03F_CD10 CHAR(4) DEFAULT ' ',
	PM03F_STTM NUMBER(8,0) DEFAULT 0,
	PM03F_USER VARCHAR(20) DEFAULT ' ',
	PM03F_CRTD NUMBER(8,0) DEFAULT 0,
	PM03F_UGGU CHAR(1) DEFAULT ' ',
	PM03F_PIGU CHAR(1) DEFAULT ' ',
	CONSTRAINT PK_PMS03FB PRIMARY KEY (PM03F_PLNT,PM03F_MODL,PM03F_USEE,PM03F_PACK,PM03F_REGN,PM03F_SERL,PM03F_DIST,PM03F_TEAM,PM03F_EXTC,PM03F_INTC)
);


-- KOMMS_ADM.PSE06AC definition

-- Drop table

-- DROP TABLE PSE06AC;

CREATE TABLE PSE06AC (
	PS06A_PLGU CHAR(1) NOT NULL,
	PS06A_BASE CHAR(1) NOT NULL,
	PS06A_PLNT CHAR(2) NOT NULL,
	PS06A_LINE CHAR(2) NOT NULL,
	PS06A_MODL CHAR(2) NOT NULL,
	PS06A_PDAT NUMBER(8,0) NOT NULL,
	PS06A_EDAT NUMBER(8,0) NOT NULL,
	PS06A_PROC CHAR(2) NOT NULL,
	PS06A_ORDR CHAR(9) NOT NULL,
	PS06A_DIST CHAR(5) NOT NULL,
	PS06A_EXTC CHAR(3) NOT NULL,
	PS06A_INTC CHAR(3) NOT NULL,
	PS06A_MTGU CHAR(1) NOT NULL,
	PS06A_PQTY NUMBER(5,0) DEFAULT 0,
	PS06A_STTM NUMBER(14,0) DEFAULT 0,
	PS06A_USER CHAR(8) DEFAULT ' ',
	PS06A_AFLG CHAR(1) DEFAULT ' ',
	CONSTRAINT PK_PSE06AC PRIMARY KEY (PS06A_PLGU,PS06A_BASE,PS06A_PLNT,PS06A_LINE,PS06A_MODL,PS06A_PDAT,PS06A_EDAT,PS06A_PROC,PS06A_ORDR,PS06A_DIST,PS06A_EXTC,PS06A_INTC,PS06A_MTGU)
);


-- KOMMS_ADM.PSE07HB definition

-- Drop table

-- DROP TABLE PSE07HB;

CREATE TABLE PSE07HB (
	PS07H_PLNT CHAR(2) NOT NULL,
	PS07H_CRFD NUMBER(8,0) NOT NULL,
	PS07H_FRCD NUMBER(8,0) NOT NULL,
	PS07H_WKLD NUMBER(8,0) NOT NULL,
	PS07H_STTM NUMBER(14,0) DEFAULT NULL,
	PS07H_USER VARCHAR(20) DEFAULT NULL,
	CONSTRAINT PK_PSE07HB PRIMARY KEY (PS07H_PLNT)
);


-- KOMMS_ADM.RECIPIENTINFO definition

-- Drop table

-- DROP TABLE RECIPIENTINFO;

CREATE TABLE RECIPIENTINFO (
	MID NUMBER(9,0) NOT NULL,
	RNAME VARCHAR(50) NOT NULL,
	RMAIL VARCHAR(100) NOT NULL,
	RID VARCHAR(20),
	CONSTRAINT PK_RECIPIENTINFO PRIMARY KEY (MID)
);


-- KOMMS_ADM.SY_PMS03FB_KMC definition

-- Drop table

-- DROP TABLE SY_PMS03FB_KMC;

CREATE TABLE SY_PMS03FB_KMC (

);


-- KOMMS_ADM.SY_PSE06AC_KMC definition

-- Drop table

-- DROP TABLE SY_PSE06AC_KMC;

CREATE TABLE SY_PSE06AC_KMC (

);


-- KOMMS_ADM.SY_PSE07HB_KMC definition

-- Drop table

-- DROP TABLE SY_PSE07HB_KMC;

CREATE TABLE SY_PSE07HB_KMC (

);


-- KOMMS_ADM.TB_ABLE_ADM_LOG_TEMP definition

-- Drop table

-- DROP TABLE TB_ABLE_ADM_LOG_TEMP;

CREATE TABLE TB_ABLE_ADM_LOG_TEMP (
	WK_YMD VARCHAR(8),
	IDX CHAR(2),
	VALUE NUMBER(8,0)
);


-- KOMMS_ADM.TB_ACT_AUTH definition

-- Drop table

-- DROP TABLE TB_ACT_AUTH;

CREATE TABLE TB_ACT_AUTH (
	USER_EENO VARCHAR(20) NOT NULL,
	ACT_ID VARCHAR(50) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	CONSTRAINT PK_TB_ACT_AUTH PRIMARY KEY (USER_EENO,ACT_ID)
);


-- KOMMS_ADM.TB_ACT_MGMT definition

-- Drop table

-- DROP TABLE TB_ACT_MGMT;

CREATE TABLE TB_ACT_MGMT (
	ACT_SN NUMBER(9,0) NOT NULL,
	ACT_ID VARCHAR(50) NOT NULL,
	MENU_ID VARCHAR(4) NOT NULL,
	ACT_NM VARCHAR(100) NOT NULL,
	ACT_TYPE VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT PK_TB_ACT_MGMT PRIMARY KEY (ACT_SN)
);


-- KOMMS_ADM.TB_ALC_MST_INFO definition

-- Drop table

-- DROP TABLE TB_ALC_MST_INFO;

CREATE TABLE TB_ALC_MST_INFO (
	PRDN_MST_VEHL_CD VARCHAR(4) NOT NULL,
	BN_SN CHAR(6) NOT NULL,
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	VIN CHAR(17) NOT NULL,
	T10PS1_YMDHM CHAR(12) NOT NULL,
	T11PS1_YMDHM CHAR(12),
	FRAM_DTM DATE,
	MDFY_DTM DATE,
	CONSTRAINT TB_ALC_MST_INFO_PK PRIMARY KEY (PRDN_MST_VEHL_CD,BN_SN,DL_EXPD_CO_CD,VIN)
);
CREATE INDEX TB_ALC_MST_INFO_IDX1 ON TB_ALC_MST_INFO (T10PS1_YMDHM,PRDN_MST_VEHL_CD,BN_SN,DL_EXPD_CO_CD);
CREATE INDEX TB_ALC_MST_INFO_IDX2 ON TB_ALC_MST_INFO (T11PS1_YMDHM,PRDN_MST_VEHL_CD,BN_SN,DL_EXPD_CO_CD);


-- KOMMS_ADM.TB_ALTN_NATL_MGMT definition

-- Drop table

-- DROP TABLE TB_ALTN_NATL_MGMT;

CREATE TABLE TB_ALTN_NATL_MGMT (
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	DL_EXPD_NAT_CD VARCHAR(5) NOT NULL,
	DYTM_PLN_NAT_CD VARCHAR(5) NOT NULL,
	PRVS_SCN_CD CHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_ALTN_NATL_MGMT_PK PRIMARY KEY (DL_EXPD_CO_CD,DL_EXPD_NAT_CD,DYTM_PLN_NAT_CD,PRVS_SCN_CD)
);


-- KOMMS_ADM.TB_ALTN_VEHL_MGMT definition

-- Drop table

-- DROP TABLE TB_ALTN_VEHL_MGMT;

CREATE TABLE TB_ALTN_VEHL_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	PRDN_VEHL_CD VARCHAR(4) NOT NULL,
	PRVS_SCN_CD CHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	ET_YN CHAR(1),
	CONSTRAINT TB_ALTN_VEHL_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,PRDN_VEHL_CD,PRVS_SCN_CD)
);
CREATE INDEX TB_ALTN_VEHL_MGMT_IDX1 ON TB_ALTN_VEHL_MGMT (PRDN_VEHL_CD,PRVS_SCN_CD);


-- KOMMS_ADM.TB_ALTN_WIOUT_NATL_MGMT definition

-- Drop table

-- DROP TABLE TB_ALTN_WIOUT_NATL_MGMT;

CREATE TABLE TB_ALTN_WIOUT_NATL_MGMT (
	DL_EXPD_CO_CD VARCHAR(2) NOT NULL,
	DL_EXPD_NAT_CD VARCHAR(5) NOT NULL,
	DYTM_PLN_NAT_CD VARCHAR(5) NOT NULL,
	PRVS_SCN_CD VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT PK_TB_ALTN_WIOUT_NATL_MGMT PRIMARY KEY (DL_EXPD_CO_CD,DL_EXPD_NAT_CD,DYTM_PLN_NAT_CD,PRVS_SCN_CD)
);


-- KOMMS_ADM.TB_APS_ODR_ACUM_INFO definition

-- Drop table

-- DROP TABLE TB_APS_ODR_ACUM_INFO;

CREATE TABLE TB_APS_ODR_ACUM_INFO (
	MO_PACK_CD VARCHAR(4) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	APL_YMD CHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	ORD_QTY NUMBER(15,0) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	MDFY_DTM DATE NOT NULL,
	CONSTRAINT TB_APS_ODR_ACUM_INFO_PK PRIMARY KEY (MO_PACK_CD,DATA_SN,APL_YMD)
);
CREATE UNIQUE INDEX TB_APS_ODR_ACUM_INFO_IDX1 ON TB_APS_ODR_ACUM_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,MO_PACK_CD,APL_YMD);


-- KOMMS_ADM.TB_APS_ODR_INFO definition

-- Drop table

-- DROP TABLE TB_APS_ODR_INFO;

CREATE TABLE TB_APS_ODR_INFO (
	PRDN_ORD_NO VARCHAR(15) NOT NULL,
	DYTM_PLN_NAT_CD VARCHAR(5) NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) NOT NULL,
	DYTM_PLN_VEHL_CD VARCHAR(4) NOT NULL,
	USF_CD VARCHAR(2) NOT NULL,
	MO_PACK_CD VARCHAR(4) NOT NULL,
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	APL_STRT_YMD CHAR(8) NOT NULL,
	APL_FNH_YMD CHAR(8) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4) NOT NULL,
	BASC_MDL_CD VARCHAR(12),
	DEST_NAT_CD VARCHAR(5) NOT NULL,
	ORD_QTY NUMBER(15,0) NOT NULL,
	PRDN_PLN_QTY NUMBER(9,0) NOT NULL,
	PRDN_OCN_CD VARCHAR(4),
	VER_CD VARCHAR(3),
	FRAM_DTM DATE NOT NULL,
	QLTY_VEHL_CD VARCHAR(4),
	MDL_MDY_CD VARCHAR(2),
	DL_EXPD_NAT_CD VARCHAR(5),
	CONSTRAINT TB_APS_ODR_INFO_PK PRIMARY KEY (PRDN_ORD_NO,DYTM_PLN_NAT_CD,PRDN_PLNT_CD,DYTM_PLN_VEHL_CD,USF_CD,MO_PACK_CD,DL_EXPD_CO_CD,APL_STRT_YMD,APL_FNH_YMD)
);
CREATE INDEX TB_APS_ODR_INFO_IDX1 ON TB_APS_ODR_INFO (DL_EXPD_CO_CD,APL_STRT_YMD,APL_FNH_YMD);
CREATE INDEX TB_APS_ODR_INFO_IDX2 ON TB_APS_ODR_INFO (DL_EXPD_CO_CD,QLTY_VEHL_CD);


-- KOMMS_ADM.TB_APS_ODR_NOAPIM_INFO definition

-- Drop table

-- DROP TABLE TB_APS_ODR_NOAPIM_INFO;

CREATE TABLE TB_APS_ODR_NOAPIM_INFO (
	APL_YMD CHAR(8) NOT NULL,
	MO_PACK_CD VARCHAR(4) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(4) NOT NULL,
	DYTM_PLN_NAT_CD VARCHAR(5) NOT NULL,
	ORD_QTY NUMBER(15,0) NOT NULL,
	PRDN_PLN_QTY NUMBER(9,0) NOT NULL,
	FRAM_DTM DATE,
	MDFY_DTM DATE NOT NULL,
	CONSTRAINT TB_APS_ODR_NOAPIM_INFO_PK PRIMARY KEY (APL_YMD,QLTY_VEHL_CD,MDL_MDY_CD,DYTM_PLN_NAT_CD,MO_PACK_CD)
);


-- KOMMS_ADM.TB_APS_ODR_SUM_INFO definition

-- Drop table

-- DROP TABLE TB_APS_ODR_SUM_INFO;

CREATE TABLE TB_APS_ODR_SUM_INFO (
	APL_STRT_YMD CHAR(8) NOT NULL,
	APL_FNH_YMD CHAR(8) NOT NULL,
	MO_PACK_CD VARCHAR(4) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	ORD_QTY NUMBER(15,0) NOT NULL,
	PRDN_PLN_QTY NUMBER(9,0) NOT NULL,
	PRDN_QTY NUMBER(9,0) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	CONSTRAINT TB_APS_ODR_SUM_INFO_PK PRIMARY KEY (APL_STRT_YMD,APL_FNH_YMD,MO_PACK_CD,DATA_SN)
);
CREATE UNIQUE INDEX TB_APS_ODR_SUM_INFO_IDX1 ON TB_APS_ODR_SUM_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,APL_STRT_YMD,APL_FNH_YMD,MO_PACK_CD);


-- KOMMS_ADM.TB_APS_PLAN_NOAPIM_INFO definition

-- Drop table

-- DROP TABLE TB_APS_PLAN_NOAPIM_INFO;

CREATE TABLE TB_APS_PLAN_NOAPIM_INFO (
	APL_YMD CHAR(8) NOT NULL,
	PLN_PARR_YMD CHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(4) NOT NULL,
	DYTM_PLN_NAT_CD VARCHAR(5) NOT NULL,
	PRDN_PLN_QTY NUMBER(9,0) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	MDFY_DTM DATE,
	CONSTRAINT TB_APS_PLAN_NOAPIM_INFO_PK PRIMARY KEY (APL_YMD,QLTY_VEHL_CD,MDL_MDY_CD,DYTM_PLN_NAT_CD,PLN_PARR_YMD)
);


-- KOMMS_ADM.TB_APS_PROD_PLAN_INFO definition

-- Drop table

-- DROP TABLE TB_APS_PROD_PLAN_INFO;

CREATE TABLE TB_APS_PROD_PLAN_INFO (
	PRDN_ORD_NO VARCHAR(15) NOT NULL,
	DYTM_PLN_NAT_CD VARCHAR(5) NOT NULL,
	PRDN_PLN_SCN_CD CHAR(1) NOT NULL,
	APL_CRTN_CD CHAR(1) NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) NOT NULL,
	DYTM_PLN_VEHL_CD VARCHAR(4) NOT NULL,
	PLN_PARR_YMD CHAR(8) NOT NULL,
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	APL_STRT_YMD CHAR(8) NOT NULL,
	APL_FNH_YMD CHAR(8) NOT NULL,
	DEST_NAT_CD VARCHAR(5) NOT NULL,
	MO_PACK_CD VARCHAR(4) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4) NOT NULL,
	PRDN_PLN_QTY NUMBER(9,0) NOT NULL,
	DCSN_YN CHAR(1) NOT NULL,
	DCSN_YMD CHAR(8),
	FRAM_DTM DATE NOT NULL,
	QLTY_VEHL_CD VARCHAR(4),
	MDL_MDY_CD VARCHAR(2),
	DL_EXPD_NAT_CD VARCHAR(5),
	CONSTRAINT TB_APS_PROD_PLAN_INFO_PK PRIMARY KEY (PRDN_ORD_NO,DYTM_PLN_NAT_CD,PRDN_PLN_SCN_CD,APL_CRTN_CD,PRDN_PLNT_CD,DYTM_PLN_VEHL_CD,PLN_PARR_YMD,DL_EXPD_CO_CD,APL_STRT_YMD,APL_FNH_YMD)
);
CREATE INDEX TB_APS_PROD_PLAN_INFO_IDX1 ON TB_APS_PROD_PLAN_INFO (DL_EXPD_CO_CD,APL_STRT_YMD,APL_FNH_YMD);
CREATE INDEX TB_APS_PROD_PLAN_INFO_IDX2 ON TB_APS_PROD_PLAN_INFO (DL_EXPD_CO_CD,APL_STRT_YMD,APL_FNH_YMD,QLTY_VEHL_CD,MDL_MDY_CD,DL_EXPD_NAT_CD);
CREATE INDEX TB_APS_PROD_PLAN_INFO_IDX3 ON TB_APS_PROD_PLAN_INFO (QLTY_VEHL_CD,MDL_MDY_CD,PLN_PARR_YMD,DL_EXPD_NAT_CD);


-- KOMMS_ADM.TB_APS_PROD_PLAN_SUM_INFO definition

-- Drop table

-- DROP TABLE TB_APS_PROD_PLAN_SUM_INFO;

CREATE TABLE TB_APS_PROD_PLAN_SUM_INFO (
	APL_STRT_YMD CHAR(8) NOT NULL,
	APL_FNH_YMD CHAR(8) NOT NULL,
	PLN_PARR_YMD CHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	PRDN_PLN_QTY NUMBER(9,0) NOT NULL,
	DCSN_YN CHAR(1) NOT NULL,
	DCSN_YMD CHAR(8),
	FRAM_DTM DATE NOT NULL,
	CONSTRAINT TB_APS_PROD_PLAN_SUM_INFO_PK PRIMARY KEY (APL_STRT_YMD,APL_FNH_YMD,PLN_PARR_YMD,DATA_SN)
);
CREATE UNIQUE INDEX TB_APS_PROD_PLAN_SUM_INFO_IDX1 ON TB_APS_PROD_PLAN_SUM_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,APL_STRT_YMD,APL_FNH_YMD,PLN_PARR_YMD);


-- KOMMS_ADM.TB_APS_PROD_SUM_INFO definition

-- Drop table

-- DROP TABLE TB_APS_PROD_SUM_INFO;

CREATE TABLE TB_APS_PROD_SUM_INFO (
	APL_YMD CHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	TMM_ORD_QTY NUMBER(9,0),
	BORD_QTY NUMBER(9,0),
	TDD_PRDN_PLN_QTY NUMBER(9,0),
	WEK2_PRDN_PLN_QTY NUMBER(9,0),
	TMM_PRDN_PLN_QTY NUMBER(9,0),
	MTH3_MO_AVG_TRWI_QTY NUMBER(9,0),
	TMM_TRWI_QTY NUMBER(9,0),
	BOD_TRWI_QTY NUMBER(9,0),
	TDD_PRDN_QTY NUMBER(9,0),
	YER1_DLY_AVG_TRWI_QTY NUMBER(9,0),
	MTH3_DLY_AVG_TRWI_QTY NUMBER(9,0),
	WEK2_DLY_AVG_TRWI_QTY NUMBER(9,0),
	AVP_TRWI_QTY NUMBER(9,0),
	FRAM_DTM DATE NOT NULL,
	MDFY_DTM DATE NOT NULL,
	TDD_PRDN_QTY2 NUMBER(9,0),
	TDD_PRDN_PLN_QTY2 NUMBER(9,0),
	TDD_PRDN_PLN_QTY3 NUMBER(9,0),
	TDD_PRDN_QTY3 NUMBER(9,0),
	WEK1_DLY_AVG_TRWI_QTY NUMBER(9,0),
	CONSTRAINT TB_APS_PROD_SUM_INFO_PK PRIMARY KEY (APL_YMD,DATA_SN)
);
CREATE UNIQUE INDEX TB_APS_PROD_SUM_INFO_IDX1 ON TB_APS_PROD_SUM_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,APL_YMD);


-- KOMMS_ADM.TB_ATTC_MGMT definition

-- Drop table

-- DROP TABLE TB_ATTC_MGMT;

CREATE TABLE TB_ATTC_MGMT (
	ATTC_SN NUMBER(15,0) NOT NULL,
	ATTC_GBN VARCHAR(10) NOT NULL,
	GBN_SN VARCHAR(30) NOT NULL,
	FILE_TYPE VARCHAR(20) NOT NULL,
	FILE_NM VARCHAR(400) NOT NULL,
	FILE_RE_NM VARCHAR(400) NOT NULL,
	FILE_PATH VARCHAR(400) NOT NULL,
	FILE_SIZE NUMBER(15,0) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	CONSTRAINT PK_TB_ATTC_MGMT PRIMARY KEY (ATTC_SN)
);


-- KOMMS_ADM.TB_AUTH_AFFR_MGMT definition

-- Drop table

-- DROP TABLE TB_AUTH_AFFR_MGMT;

CREATE TABLE TB_AUTH_AFFR_MGMT (
	USER_EENO VARCHAR(20) NOT NULL,
	MENU_ID VARCHAR(10) NOT NULL,
	MENU_AUTH_CD VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	USE_YN VARCHAR(1) DEFAULT 'Y' NOT NULL,
	CONSTRAINT TB_AUTH_AFFR_MGMT_PK PRIMARY KEY (USER_EENO,MENU_ID)
);


-- KOMMS_ADM.TB_AUTH_VEHL definition

-- Drop table

-- DROP TABLE TB_AUTH_VEHL;

CREATE TABLE TB_AUTH_VEHL (
	USER_EENO VARCHAR(20) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	CL_SCN_CD VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT PK_TB_AUTH_VEHL PRIMARY KEY (USER_EENO,QLTY_VEHL_CD)
);


-- KOMMS_ADM.TB_AUTH_VEHL_MGMT definition

-- Drop table

-- DROP TABLE TB_AUTH_VEHL_MGMT;

CREATE TABLE TB_AUTH_VEHL_MGMT (
	USER_EENO VARCHAR(7) NOT NULL,
	MENU_ID VARCHAR(10) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	CL_SCN_CD VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_AUTH_VEHL_MGMT_PK PRIMARY KEY (USER_EENO,MENU_ID,QLTY_VEHL_CD,CL_SCN_CD)
);


-- KOMMS_ADM.TB_BATCH_ERP_ET_INFO definition

-- Drop table

-- DROP TABLE TB_BATCH_ERP_ET_INFO;

CREATE TABLE TB_BATCH_ERP_ET_INFO (
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	BTCH_FNH_YMD CHAR(8) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
	ET_GUBN_CD CHAR(2) NOT NULL,
	FRAM_DTM DATE DEFAULT SYSDATE NOT NULL,
	CONSTRAINT TB_BATCH_ERP_ET_INFO_PK PRIMARY KEY (DL_EXPD_CO_CD,BTCH_FNH_YMD,ET_GUBN_CD)
);


-- KOMMS_ADM.TB_BATCH_EXE_LOG definition

-- Drop table

-- DROP TABLE TB_BATCH_EXE_LOG;

CREATE TABLE TB_BATCH_EXE_LOG (
	LOG_SN NUMBER(10,0) NOT NULL,
	BTCH_NM VARCHAR(100),
	BTCH_FNH_STRT_DTM DATE,
	BTCH_FNH_DTM DATE,
	BTCH_WK_CD VARCHAR(3),
	BTCH_WK_RSLT_SBC VARCHAR(400),
	CONSTRAINT PK_TB_BATCH_EXE_LOG PRIMARY KEY (LOG_SN)
);


-- KOMMS_ADM.TB_BATCH_FNH_INFO definition

-- Drop table

-- DROP TABLE TB_BATCH_FNH_INFO;

CREATE TABLE TB_BATCH_FNH_INFO (
	AFFR_SCN_CD VARCHAR(4) NOT NULL,
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	BTCH_FNH_YMD CHAR(8) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	CONSTRAINT TB_BATCH_FNH_INFO_PK PRIMARY KEY (AFFR_SCN_CD,DL_EXPD_CO_CD,BTCH_FNH_YMD)
);


-- KOMMS_ADM.TB_BATCH_RSLT_INFO definition

-- Drop table

-- DROP TABLE TB_BATCH_RSLT_INFO;

CREATE TABLE TB_BATCH_RSLT_INFO (
	BTCH_NM VARCHAR(100) NOT NULL,
	BTCH_FIN_STRT_DTM DATE NOT NULL,
	BTCH_FNH_DTM DATE NOT NULL,
	BTCH_WK_CD VARCHAR(3) NOT NULL,
	BTCH_WK_RSLT_SBC VARCHAR(4000),
	CONSTRAINT TB_BATCH_RSLT_INFO_PK PRIMARY KEY (BTCH_NM,BTCH_FIN_STRT_DTM,BTCH_FNH_DTM)
);


-- KOMMS_ADM.TB_BOARD_MGMT definition

-- Drop table

-- DROP TABLE TB_BOARD_MGMT;

CREATE TABLE TB_BOARD_MGMT (
	SCRN_SN NUMBER(9,0) NOT NULL,
	AFFR_SCN_CD VARCHAR(2) NOT NULL,
	RGN_EENO VARCHAR(20) NOT NULL,
	BLC_RGST_YMD VARCHAR(8) NOT NULL,
	BLC_TITL_NM VARCHAR(100),
	BLC_SBC CLOB,
	ATTC_YN VARCHAR(1),
	N1AFP2_ADR VARCHAR(200),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	BUL_STRT_YMD VARCHAR(8),
	BUL_FNH_YMD VARCHAR(8),
	BUL_YN VARCHAR(1),
	CONSTRAINT TB_BOARD_MGMT_PK PRIMARY KEY (SCRN_SN)
);


-- KOMMS_ADM.TB_BOARD_SUBJ_MGMT definition

-- Drop table

-- DROP TABLE TB_BOARD_SUBJ_MGMT;

CREATE TABLE TB_BOARD_SUBJ_MGMT (
	SCRN_SN NUMBER(9,0) NOT NULL,
	BUL_SUBJ_CD VARCHAR(20) NOT NULL,
	SORT_SN NUMBER(3,0) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	BOARD_NO NUMBER(9,0) NOT NULL,
	POP_CK_DTM VARCHAR(8),
	CONSTRAINT TB_BOARD_SUBJ_MGMT_PK PRIMARY KEY (SCRN_SN,BUL_SUBJ_CD)
);


-- KOMMS_ADM.TB_CHKLIST_DTL_INFO definition

-- Drop table

-- DROP TABLE TB_CHKLIST_DTL_INFO;

CREATE TABLE TB_CHKLIST_DTL_INFO (
	DL_EXPD_ALTR_NO VARCHAR(10) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	ET_YN CHAR(1),
	CONSTRAINT TB_CHKLIST_DTL_INFO_PK PRIMARY KEY (DL_EXPD_ALTR_NO,QLTY_VEHL_CD,LANG_CD)
);
CREATE INDEX TB_CHKLIST_DTL_INFO_IDX1 ON TB_CHKLIST_DTL_INFO (QLTY_VEHL_CD,LANG_CD,N_PRNT_PBCN_NO);


-- KOMMS_ADM.TB_CHKLIST_DTL_INFO_IF definition

-- Drop table

-- DROP TABLE TB_CHKLIST_DTL_INFO_IF;

CREATE TABLE TB_CHKLIST_DTL_INFO_IF (
	DTL_SN NUMBER(11,0) NOT NULL,
	DL_EXPD_ALTR_NO VARCHAR(10) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	IF_WK_RSLT_CD CHAR(1),
	CONSTRAINT TB_CHKLIST_DTL_INFO_IF_PK PRIMARY KEY (DTL_SN)
);


-- KOMMS_ADM.TB_CHKLIST_INFO definition

-- Drop table

-- DROP TABLE TB_CHKLIST_INFO;

CREATE TABLE TB_CHKLIST_INFO (
	DL_EXPD_ALTR_NO VARCHAR(10) NOT NULL,
	ALTR_YMD CHAR(8) NOT NULL,
	RCPM_SHAP_CD VARCHAR(4) NOT NULL,
	DSPP_NM VARCHAR(100),
	CHGR_EENO VARCHAR(20) NOT NULL,
	CRGR_NM VARCHAR(100),
	ALTR_SBC CLOB,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	DEL_YN CHAR(1),
	N1AFP2_ADR VARCHAR(200),
	N1AFP2_ADR1 VARCHAR(200),
	ET_YN CHAR(1),
	ATTC_YN CHAR(1),
	CONSTRAINT TB_CHKLIST_INFO_PK PRIMARY KEY (DL_EXPD_ALTR_NO)
);


-- KOMMS_ADM.TB_CODE_GRP_MGMT definition

-- Drop table

-- DROP TABLE TB_CODE_GRP_MGMT;

CREATE TABLE TB_CODE_GRP_MGMT (
	DL_EXPD_G_CD VARCHAR(4) NOT NULL,
	DL_EXPD_G_NM VARCHAR(200),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_CODE_GRP_MGMT_PK PRIMARY KEY (DL_EXPD_G_CD)
);


-- KOMMS_ADM.TB_CODE_MGMT definition

-- Drop table

-- DROP TABLE TB_CODE_MGMT;

CREATE TABLE TB_CODE_MGMT (
	DL_EXPD_G_CD VARCHAR(4) NOT NULL,
	DL_EXPD_PRVS_CD VARCHAR(4) NOT NULL,
	DL_EXPD_PRVS_NM VARCHAR(200),
	SORT_SN NUMBER(3,0) NOT NULL,
	USE_YN VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_CODE_MGMT_PK PRIMARY KEY (DL_EXPD_G_CD,DL_EXPD_PRVS_CD)
);


-- KOMMS_ADM.TB_DL_EXPD_MDY_MGMT definition

-- Drop table

-- DROP TABLE TB_DL_EXPD_MDY_MGMT;

CREATE TABLE TB_DL_EXPD_MDY_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	DL_EXPD_REGN_CD VARCHAR(4) NOT NULL,
	CONSTRAINT TB_DL_EXPD_MDY_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,MDL_MDY_CD,DL_EXPD_REGN_CD,DL_EXPD_MDL_MDY_CD)
);


-- KOMMS_ADM.TB_DL_LANG_MDY_MGMT definition

-- Drop table

-- DROP TABLE TB_DL_LANG_MDY_MGMT;

CREATE TABLE TB_DL_LANG_MDY_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	DL_EXPD_REGN_CD VARCHAR(4) NOT NULL,
	CONSTRAINT TB_DL_LANG_MDY_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,LANG_CD,MDL_MDY_CD,DL_EXPD_REGN_CD,DL_EXPD_MDL_MDY_CD)
);


-- KOMMS_ADM.TB_EO_CD_INFO definition

-- Drop table

-- DROP TABLE TB_EO_CD_INFO;

CREATE TABLE TB_EO_CD_INFO (
	DL_EXPD_ALTR_NO VARCHAR(10) NOT NULL,
	EO_CD VARCHAR(100) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	CONSTRAINT TB_EO_CD_INFO_PK PRIMARY KEY (EO_CD,DL_EXPD_ALTR_NO)
);


-- KOMMS_ADM.TB_EXTRA_REQ_INFO definition

-- Drop table

-- DROP TABLE TB_EXTRA_REQ_INFO;

CREATE TABLE TB_EXTRA_REQ_INFO (
	RQ_YMD VARCHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	DTL_SN NUMBER(11,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DL_EXPD_RQ_SCN_CD VARCHAR(4) NOT NULL,
	CRGR_EENO VARCHAR(20),
	RQ_QTY NUMBER(5,0) NOT NULL,
	DLVH_RQ_OPS_NM VARCHAR(50),
	PWMR_EENO VARCHAR(20) NOT NULL,
	RQ_RSON_SBC VARCHAR(256),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	DLVG_YN VARCHAR(1),
	N_PRNT_PBCN_NO VARCHAR(100),
	PRDN_PLNT_CD VARCHAR(1) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_EXTRA_REQ_INFO PRIMARY KEY (RQ_YMD,DATA_SN,DTL_SN,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_GLOVIS_DLVH_REQ_INFO definition

-- Drop table

-- DROP TABLE TB_GLOVIS_DLVH_REQ_INFO;

CREATE TABLE TB_GLOVIS_DLVH_REQ_INFO (
	RQ_YMD CHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	DTL_SN NUMBER(11,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DL_EXPD_RQ_SCN_CD VARCHAR(4) NOT NULL,
	CRGR_EENO VARCHAR(20),
	PWMR_EENO VARCHAR(20) NOT NULL,
	RQ_QTY NUMBER(5,0) NOT NULL,
	DEL_YN CHAR(1) NOT NULL,
	SPMN_IMTR_SBC VARCHAR(100),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_GLOVIS_DLVH_REQ_INFO_PK PRIMARY KEY (RQ_YMD,DATA_SN,DTL_SN)
);
CREATE INDEX TB_GLOVIS_DLVH_REQ_INFO_IDX1 ON TB_GLOVIS_DLVH_REQ_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD);


-- KOMMS_ADM.TB_GLOVIS_DPCR_INFO definition

-- Drop table

-- DROP TABLE TB_GLOVIS_DPCR_INFO;

CREATE TABLE TB_GLOVIS_DPCR_INFO (
	WHOT_YMD CHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	DTL_SN NUMBER(11,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	CRGR_EENO VARCHAR(20),
	DPCR_QTY NUMBER(9,0),
	DPCR_SALE_DCSN_QTY NUMBER(9,0),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_GLOVIS_DPCR_INFO_PK PRIMARY KEY (WHOT_YMD,DATA_SN,DTL_SN)
);
CREATE INDEX TB_GLOVIS_DPCR_INFO_IDX1 ON TB_GLOVIS_DPCR_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD);


-- KOMMS_ADM.TB_LANG_MAST definition

-- Drop table

-- DROP TABLE TB_LANG_MAST;

CREATE TABLE TB_LANG_MAST (
	LANG_CD VARCHAR(3) NOT NULL,
	LANG_CD_NM VARCHAR(200),
	USE_YN VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(2),
	CONSTRAINT PK_TB_LANG_MAST PRIMARY KEY (LANG_CD)
);


-- KOMMS_ADM.TB_LANG_MGMT definition

-- Drop table

-- DROP TABLE TB_LANG_MGMT;

CREATE TABLE TB_LANG_MGMT (
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4) NOT NULL,
	LANG_CD_NM VARCHAR(200),
	USE_YN VARCHAR(1) NOT NULL,
	NAPC_YN VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	SORT_SN NUMBER(7,0),
	A_CODE VARCHAR(100),
	N1_INS_YN VARCHAR(1),
	ET_YN VARCHAR(1),
	CONSTRAINT PK_TB_LANG_MGMT PRIMARY KEY (DATA_SN)
);
CREATE INDEX TB_LANG_MGMT_IDX1 ON TB_LANG_MGMT (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD);
CREATE INDEX TB_LANG_MGMT_IDX2 ON TB_LANG_MGMT (MDL_MDY_CD,DL_EXPD_REGN_CD,LANG_CD);
CREATE INDEX TB_LANG_MGMT_IDX3 ON TB_LANG_MGMT (LANG_CD);


-- KOMMS_ADM.TB_LANG_MGMT_IF definition

-- Drop table

-- DROP TABLE TB_LANG_MGMT_IF;

CREATE TABLE TB_LANG_MGMT_IF (
	DTL_SN NUMBER(11,0) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4) NOT NULL,
	LANG_CD_NM VARCHAR(200),
	USE_YN CHAR(1) NOT NULL,
	NAPC_YN CHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	SORT_SN NUMBER(7,0),
	A_CODE VARCHAR(100),
	N1_INS_YN CHAR(1),
	IF_WK_RSLT_CD CHAR(1),
	CONSTRAINT TB_LANG_MGMT_IF_PK PRIMARY KEY (DTL_SN)
);


-- KOMMS_ADM.TB_LANG_MGMT_ORIGINAL definition

-- Drop table

-- DROP TABLE TB_LANG_MGMT_ORIGINAL;

CREATE TABLE TB_LANG_MGMT_ORIGINAL (
	LANG_CD VARCHAR(3) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4),
	LANG_CD_NM VARCHAR(200),
	CONSTRAINT TB_LANG_MGMT_ORIGINAL_PK PRIMARY KEY (LANG_CD)
);


-- KOMMS_ADM.TB_LGI_LOG definition

-- Drop table

-- DROP TABLE TB_LGI_LOG;

CREATE TABLE TB_LGI_LOG (
	LGI_LOG_SN NUMBER(10,0) NOT NULL,
	USER_ID VARCHAR(265) NOT NULL,
	LGI_DTM DATE NOT NULL,
	SUCS_YN CHAR(1) NOT NULL,
	USER_IP_ADR VARCHAR(100) NOT NULL,
	ID_EXIST_YN CHAR(1) DEFAULT 'N' NOT NULL,
	SESS_ID VARCHAR(100),
	LGO_DTM DATE,
	LGO_TYPE CHAR(1) DEFAULT NULL,
	CONSTRAINT TB_LGI_LOG_PK PRIMARY KEY (LGI_LOG_SN)
);


-- KOMMS_ADM.TB_LOG_AUTH definition

-- Drop table

-- DROP TABLE TB_LOG_AUTH;

CREATE TABLE TB_LOG_AUTH (
	ALTR_LOG_SN NUMBER(10,0) NOT NULL,
	USER_ID VARCHAR(20),
	CHGR_ID VARCHAR(20),
	CHGR_IP_ADR VARCHAR(100),
	ALTR_TYPE VARCHAR(10),
	BFRE_VALUE VARCHAR(20),
	AFTR_VALUE VARCHAR(20),
	AKTR_DTM DATE,
	CONSTRAINT PK_TB_LOG_AUTH PRIMARY KEY (ALTR_LOG_SN)
);


-- KOMMS_ADM.TB_LOG_EML definition

-- Drop table

-- DROP TABLE TB_LOG_EML;

CREATE TABLE TB_LOG_EML (
	EML_CD NUMBER(13,0) NOT NULL,
	EML_ID VARCHAR(20),
	SNDR_ID VARCHAR(20),
	ADRE_EML VARCHAR(200),
	EML_TITL VARCHAR(200),
	EML_SBC VARCHAR(300),
	EML_ST_CD VARCHAR(20),
	SND_DATE DATE,
	CONSTRAINT TB_LOG_EML PRIMARY KEY (EML_CD)
);
CREATE UNIQUE INDEX PK_TB_LOG_EML ON TB_LOG_EML (EML_CD);


-- KOMMS_ADM.TB_LOG_LGI definition

-- Drop table

-- DROP TABLE TB_LOG_LGI;

CREATE TABLE TB_LOG_LGI (
	LGI_CD NUMBER(13,0) NOT NULL,
	LGI_ID VARCHAR(20),
	LGI_IP VARCHAR(30),
	LGI_SBC VARCHAR(51),
	LGI_DATE DATE,
	CONSTRAINT PK_TB_LOG_LGI PRIMARY KEY (LGI_CD)
);


-- KOMMS_ADM.TB_LOG_USE definition

-- Drop table

-- DROP TABLE TB_LOG_USE;

CREATE TABLE TB_LOG_USE (
	USE_LOG_SN NUMBER(10,0) NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	PGM_ID VARCHAR(10) NOT NULL,
	PGM_NM VARCHAR(50),
	USE_TYPE VARCHAR(2) NOT NULL,
	FILE_NM VARCHAR(400),
	FILE_SIZE NUMBER(10,0),
	USE_DTM DATE NOT NULL,
	CONSTRAINT PK_TB_LOG_USE PRIMARY KEY (USE_LOG_SN)
);


-- KOMMS_ADM.TB_LOG_USER_ALTR definition

-- Drop table

-- DROP TABLE TB_LOG_USER_ALTR;

CREATE TABLE TB_LOG_USER_ALTR (
	ALTR_CD NUMBER(13,0) NOT NULL,
	USER_ID VARCHAR(30),
	CHGR_ID VARCHAR(30),
	CHGR_IP VARCHAR(30),
	BEFR_VALUE VARCHAR(1000),
	AFTR_VALUE VARCHAR(1000),
	BEF_AUTH VARCHAR(30),
	AFT_AUTH VARCHAR(30),
	ALTR_DATE DATE
);
CREATE UNIQUE INDEX PK_TB_LOG_USER_ALTR ON TB_LOG_USER_ALTR (ALTR_CD);


-- KOMMS_ADM.TB_MNL_MGMT definition

-- Drop table

-- DROP TABLE TB_MNL_MGMT;

CREATE TABLE TB_MNL_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	QLTY_VEHL_NM VARCHAR(100),
	LANG_CD VARCHAR(3) NOT NULL,
	LANG_CD_NM VARCHAR(200),
	REG_YN VARCHAR(1),
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	FILE_TYPE VARCHAR(20) NOT NULL,
	FILE_SN NUMBER NOT NULL,
	REG_DT DATE NOT NULL,
	REG_USER VARCHAR(20) NOT NULL
);


-- KOMMS_ADM.TB_MO_PACK_MGMT definition

-- Drop table

-- DROP TABLE TB_MO_PACK_MGMT;

CREATE TABLE TB_MO_PACK_MGMT (
	MO_PACK_CD VARCHAR(4) NOT NULL,
	CONSTRAINT TB_MO_PACK_MGMT_PK PRIMARY KEY (MO_PACK_CD)
);


-- KOMMS_ADM.TB_MSG_MGMT definition

-- Drop table

-- DROP TABLE TB_MSG_MGMT;

CREATE TABLE TB_MSG_MGMT (
	MSG_CD VARCHAR(4) NOT NULL,
	MSG_SCN_CD CHAR(1) NOT NULL,
	MSG_SBC VARCHAR(200),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_MSG_MGMT_PK PRIMARY KEY (MSG_CD,MSG_SCN_CD)
);


-- KOMMS_ADM.TB_NATL_LANG_EXCEL definition

-- Drop table

-- DROP TABLE TB_NATL_LANG_EXCEL;

CREATE TABLE TB_NATL_LANG_EXCEL (
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	DL_EXPD_NAT_CD VARCHAR(5) NOT NULL,
	NAT_NM VARCHAR(40),
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD_LIST VARCHAR(100) NOT NULL
);


-- KOMMS_ADM.TB_NATL_LANG_MGMT definition

-- Drop table

-- DROP TABLE TB_NATL_LANG_MGMT;

CREATE TABLE TB_NATL_LANG_MGMT (
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	DL_EXPD_NAT_CD VARCHAR(5) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	USE_YN CHAR(1) NOT NULL,
	NAPC_YN CHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_NATL_LANG_MGMT_PK PRIMARY KEY (DL_EXPD_CO_CD,DL_EXPD_NAT_CD,QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD)
);


-- KOMMS_ADM.TB_NATL_MGMT definition

-- Drop table

-- DROP TABLE TB_NATL_MGMT;

CREATE TABLE TB_NATL_MGMT (
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	DL_EXPD_NAT_CD VARCHAR(5) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4),
	NAT_NM VARCHAR(40),
	DYTM_PLN_NAT_CD VARCHAR(5),
	PRDN_MST_NAT_CD VARCHAR(5),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_NATL_MGMT_PK PRIMARY KEY (DL_EXPD_CO_CD,DL_EXPD_NAT_CD)
);


-- KOMMS_ADM.TB_NATL_NOAPIM_MGMT definition

-- Drop table

-- DROP TABLE TB_NATL_NOAPIM_MGMT;

CREATE TABLE TB_NATL_NOAPIM_MGMT (
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	DL_EXPD_NAT_CD VARCHAR(5) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4),
	NAT_NM VARCHAR(40),
	DYTM_PLN_NAT_CD VARCHAR(5),
	PRDN_MST_NAT_CD VARCHAR(5),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_NATL_NOAPIM_MGMT_PK PRIMARY KEY (DL_EXPD_CO_CD,DL_EXPD_NAT_CD)
);


-- KOMMS_ADM.TB_NATL_VEHL_MGMT definition

-- Drop table

-- DROP TABLE TB_NATL_VEHL_MGMT;

CREATE TABLE TB_NATL_VEHL_MGMT (
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	DL_EXPD_NAT_CD VARCHAR(5) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_NATL_VEHL_MGMT_PK PRIMARY KEY (DL_EXPD_CO_CD,DL_EXPD_NAT_CD,QLTY_VEHL_CD,DL_EXPD_REGN_CD)
);


-- KOMMS_ADM.TB_PAGE_CODE_MGMT definition

-- Drop table

-- DROP TABLE TB_PAGE_CODE_MGMT;

CREATE TABLE TB_PAGE_CODE_MGMT (
	DL_EXPD_PG_NM VARCHAR(50) NOT NULL,
	DEPPG1_CD VARCHAR(4) NOT NULL,
	DL_EXPD_PG_PRVS_CD VARCHAR(4) NOT NULL,
	DEPPH1_NM VARCHAR(200),
	DEPPE1_NM VARCHAR(200),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_PAGE_CODE_MGMT_PK PRIMARY KEY (DL_EXPD_PG_NM,DEPPG1_CD,DL_EXPD_PG_PRVS_CD)
);


-- KOMMS_ADM.TB_PDI_COM_VEHL_MGMT definition

-- Drop table

-- DROP TABLE TB_PDI_COM_VEHL_MGMT;

CREATE TABLE TB_PDI_COM_VEHL_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DIVS_QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DL_EXPD_PDI_CD VARCHAR(4),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_PDI_COM_VEHL_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,DIVS_QLTY_VEHL_CD)
);
CREATE INDEX TB_PDI_COM_VEHL_MGMT_IDX1 ON TB_PDI_COM_VEHL_MGMT (DIVS_QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD);


-- KOMMS_ADM.TB_PDI_DIVS_INFO definition

-- Drop table

-- DROP TABLE TB_PDI_DIVS_INFO;

CREATE TABLE TB_PDI_DIVS_INFO (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	WHOT_YMD CHAR(8) NOT NULL,
	DL_EXPD_RQ_SCN_CD VARCHAR(4),
	RQ_QTY NUMBER(5,0) NOT NULL,
	DIVS_QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DIVS_DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	DIVS_LANG_CD VARCHAR(3) NOT NULL,
	PRTL_IMTR_SBC VARCHAR(4000),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_PDI_DIVS_INFO_PK PRIMARY KEY (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,DL_EXPD_MDL_MDY_CD,N_PRNT_PBCN_NO,WHOT_YMD)
);
CREATE INDEX TB_PDI_DIVS_INFO_IDX1 ON TB_PDI_DIVS_INFO (WHOT_YMD,QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD);


-- KOMMS_ADM.TB_PDI_DLVH_REQ_INFO definition

-- Drop table

-- DROP TABLE TB_PDI_DLVH_REQ_INFO;

CREATE TABLE TB_PDI_DLVH_REQ_INFO (
	RQ_YMD CHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	DTL_SN NUMBER(11,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	CRGR_EENO VARCHAR(20),
	PWMR_EENO VARCHAR(20) NOT NULL,
	RQ_QTY NUMBER(5,0) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_PDI_DLVH_REQ_INFO PRIMARY KEY (RQ_YMD,DATA_SN,DTL_SN,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_PDI_IV_INFO definition

-- Drop table

-- DROP TABLE TB_PDI_IV_INFO;

CREATE TABLE TB_PDI_IV_INFO (
	CLS_YMD CHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	IV_QTY NUMBER(9,0) NOT NULL,
	CMPL_YN CHAR(1),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	TMP_TRTM_YN CHAR(1),
	DEEI1_QTY NUMBER(9,0),
	IV_SCN_CD CHAR(1),
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_PDI_IV_INFO PRIMARY KEY (CLS_YMD,QLTY_VEHL_CD,DL_EXPD_MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_PDI_IV_INFO_DTL definition

-- Drop table

-- DROP TABLE TB_PDI_IV_INFO_DTL;

CREATE TABLE TB_PDI_IV_INFO_DTL (
	CLS_YMD CHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	IV_QTY NUMBER(9,0) NOT NULL,
	SFTY_IV_QTY NUMBER(9,0) NOT NULL,
	CMPL_YN CHAR(1),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	TMP_TRTM_YN CHAR(1),
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_PDI_IV_INFO_DTL PRIMARY KEY (CLS_YMD,QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,DL_EXPD_MDL_MDY_CD,N_PRNT_PBCN_NO,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_PDI_WHOT_INFO definition

-- Drop table

-- DROP TABLE TB_PDI_WHOT_INFO;

CREATE TABLE TB_PDI_WHOT_INFO (
	WHOT_YMD CHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	DTL_SN NUMBER(11,0) NOT NULL,
	DL_EXPD_WHOT_ST_CD VARCHAR(4) NOT NULL,
	CRGR_EENO VARCHAR(20),
	DL_EXPD_WHOT_QTY NUMBER(9,0) NOT NULL,
	DEL_YN CHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	PRTL_IMTR_SBC VARCHAR(4000),
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_PDI_WHOT_INFO PRIMARY KEY (WHOT_YMD,QLTY_VEHL_CD,DL_EXPD_MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO,DTL_SN,MDL_MDY_CD,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_PDI_WHSN_INFO definition

-- Drop table

-- DROP TABLE TB_PDI_WHSN_INFO;

CREATE TABLE TB_PDI_WHSN_INFO (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	DTL_SN NUMBER(11,0) NOT NULL,
	WHSN_YMD CHAR(8) NOT NULL,
	DL_EXPD_WHSN_ST_CD VARCHAR(4) NOT NULL,
	WHSN_QTY NUMBER(9,0) NOT NULL,
	DEEI1_QTY NUMBER(9,0),
	CRGR_EENO VARCHAR(20),
	DL_EXPD_BOX_QTY NUMBER(9,0),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_PDI_WHSN_INFO PRIMARY KEY (QLTY_VEHL_CD,DL_EXPD_MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO,DTL_SN,MDL_MDY_CD,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_PGM_MGMT definition

-- Drop table

-- DROP TABLE TB_PGM_MGMT;

CREATE TABLE TB_PGM_MGMT (
	MENU_ID VARCHAR(10) NOT NULL,
	PGM_ID VARCHAR(10) NOT NULL,
	PGM_ID_SN NUMBER(5,0) NOT NULL,
	PGM_NM VARCHAR(50),
	PGM_PATH_ADR VARCHAR(256),
	INP_SCN_CD VARCHAR(1) NOT NULL,
	USE_YN VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_PGM_MGMT_PK PRIMARY KEY (MENU_ID)
);


-- KOMMS_ADM.TB_PLNT_APS_ODR_SUM_INFO definition

-- Drop table

-- DROP TABLE TB_PLNT_APS_ODR_SUM_INFO;

CREATE TABLE TB_PLNT_APS_ODR_SUM_INFO (
	APL_STRT_YMD CHAR(8) NOT NULL,
	APL_FNH_YMD CHAR(8) NOT NULL,
	MO_PACK_CD VARCHAR(4) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	ORD_QTY NUMBER(15,0) NOT NULL,
	PRDN_PLN_QTY NUMBER(9,0) NOT NULL,
	PRDN_QTY NUMBER(9,0) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) NOT NULL,
	CONSTRAINT TB_PLNT_APS_ODR_SUM_INFO_PK PRIMARY KEY (APL_STRT_YMD,APL_FNH_YMD,MO_PACK_CD,DATA_SN,PRDN_PLNT_CD)
);
CREATE UNIQUE INDEX TB_PLNT_APS_ODR_SUM_INFO_IDX1 ON TB_PLNT_APS_ODR_SUM_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,APL_STRT_YMD,APL_FNH_YMD,MO_PACK_CD,PRDN_PLNT_CD);


-- KOMMS_ADM.TB_PLNT_APS_PROD_PLAN_SUM_INFO definition

-- Drop table

-- DROP TABLE TB_PLNT_APS_PROD_PLAN_SUM_INFO;

CREATE TABLE TB_PLNT_APS_PROD_PLAN_SUM_INFO (
	APL_STRT_YMD CHAR(8) NOT NULL,
	APL_FNH_YMD CHAR(8) NOT NULL,
	PLN_PARR_YMD CHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	PRDN_PLN_QTY NUMBER(9,0) NOT NULL,
	DCSN_YN CHAR(1) NOT NULL,
	DCSN_YMD CHAR(8),
	FRAM_DTM DATE NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) NOT NULL,
	CONSTRAINT TB_PLNT_APS_PLAN_SUM_INFO_PK PRIMARY KEY (APL_STRT_YMD,APL_FNH_YMD,PLN_PARR_YMD,DATA_SN,PRDN_PLNT_CD)
);
CREATE UNIQUE INDEX TB_PLNT_APS_PLAN_SUM_INFO_IDX1 ON TB_PLNT_APS_PROD_PLAN_SUM_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,APL_STRT_YMD,APL_FNH_YMD,PLN_PARR_YMD,PRDN_PLNT_CD);


-- KOMMS_ADM.TB_PLNT_APS_PROD_SUM_INFO definition

-- Drop table

-- DROP TABLE TB_PLNT_APS_PROD_SUM_INFO;

CREATE TABLE TB_PLNT_APS_PROD_SUM_INFO (
	APL_YMD CHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	TMM_ORD_QTY NUMBER(9,0),
	BORD_QTY NUMBER(9,0),
	TDD_PRDN_PLN_QTY NUMBER(9,0),
	WEK2_PRDN_PLN_QTY NUMBER(9,0),
	TMM_PRDN_PLN_QTY NUMBER(9,0),
	MTH3_MO_AVG_TRWI_QTY NUMBER(9,0),
	TMM_TRWI_QTY NUMBER(9,0),
	BOD_TRWI_QTY NUMBER(9,0),
	TDD_PRDN_QTY NUMBER(9,0),
	YER1_DLY_AVG_TRWI_QTY NUMBER(9,0),
	MTH3_DLY_AVG_TRWI_QTY NUMBER(9,0),
	WEK2_DLY_AVG_TRWI_QTY NUMBER(9,0),
	AVP_TRWI_QTY NUMBER(9,0),
	FRAM_DTM DATE NOT NULL,
	MDFY_DTM DATE NOT NULL,
	TDD_PRDN_QTY2 NUMBER(9,0),
	TDD_PRDN_PLN_QTY2 NUMBER(9,0),
	TDD_PRDN_PLN_QTY3 NUMBER(9,0),
	TDD_PRDN_QTY3 NUMBER(9,0),
	WEK1_DLY_AVG_TRWI_QTY NUMBER(9,0),
	PRDN_PLNT_CD VARCHAR(3) NOT NULL,
	CONSTRAINT TB_PLNT_APS_PROD_SUM_INFO_PK PRIMARY KEY (APL_YMD,DATA_SN,PRDN_PLNT_CD)
);
CREATE UNIQUE INDEX TB_PLNT_APS_PROD_SUM_INFO_IDX1 ON TB_PLNT_APS_PROD_SUM_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,APL_YMD,PRDN_PLNT_CD);


-- KOMMS_ADM.TB_PLNT_PROD_MST_SUM_INFO definition

-- Drop table

-- DROP TABLE TB_PLNT_PROD_MST_SUM_INFO;

CREATE TABLE TB_PLNT_PROD_MST_SUM_INFO (
	APL_YMD CHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	PRDN_TRWI_QTY NUMBER(9,0) NOT NULL,
	PRDN_QTY NUMBER(9,0) NOT NULL,
	TH1_POW_STRT_YMDHM CHAR(12),
	TH1_POW_FNH_YMDHM CHAR(12),
	TH1_POW_TRWI_QTY NUMBER(9,0),
	TH2_POW_STRT_YMDHM CHAR(12),
	TH2_POW_FNH_YMDHM CHAR(12),
	TH2_POW_TRWI_QTY NUMBER(9,0),
	TH3_POW_STRT_YMDHM CHAR(12),
	TH3_POW_FNH_YMDHM CHAR(12),
	TH3_POW_TRWI_QTY NUMBER(9,0),
	TH4_POW_STRT_YMDHM CHAR(12),
	TH4_POW_FNH_YMDHM CHAR(12),
	TH4_POW_TRWI_QTY NUMBER(9,0),
	TH5_POW_STRT_YMDHM CHAR(12),
	TH5_POW_FNH_YMDHM CHAR(12),
	TH5_POW_TRWI_QTY NUMBER(9,0),
	TH6_POW_STRT_YMDHM CHAR(12),
	TH6_POW_FNH_YMDHM CHAR(12),
	TH6_POW_TRWI_QTY NUMBER(9,0),
	TH7_POW_STRT_YMDHM CHAR(12),
	TH7_POW_FNH_YMDHM CHAR(12),
	TH7_POW_TRWI_QTY NUMBER(9,0),
	TH8_POW_STRT_YMDHM CHAR(12),
	TH8_POW_FNH_YMDHM CHAR(12),
	TH8_POW_TRWI_QTY NUMBER(9,0),
	TH9_POW_STRT_YMDHM CHAR(12),
	TH9_POW_FNH_YMDHM CHAR(12),
	TH9_POW_TRWI_QTY NUMBER(9,0),
	T10PS1_YMDHM CHAR(12),
	TH10_POW_FNH_YMDHM CHAR(12),
	TH10_POW_TRWI_QTY NUMBER(9,0),
	T11PS1_YMDHM CHAR(12),
	TH11_POW_FNH_YMDHM CHAR(12),
	TH11_POW_TRWI_QTY NUMBER(9,0),
	T12PS1_YMDHM CHAR(12),
	TH12_POW_FNH_YMDHM CHAR(12),
	TH12_POW_TRWI_QTY NUMBER(9,0),
	T13PS1_YMDHM CHAR(12),
	TH13_POW_FNH_YMDHM CHAR(12),
	TH13_POW_TRWI_QTY NUMBER(9,0),
	T14PS1_YMDHM CHAR(12),
	TH14_POW_FNH_YMDHM CHAR(12),
	TH14_POW_TRWI_QTY NUMBER(9,0),
	T15PS1_YMDHM CHAR(12),
	TH15_POW_FNH_YMDHM CHAR(12),
	TH15_POW_TRWI_QTY NUMBER(9,0),
	T16PS1_YMDHM CHAR(12),
	TH16_POW_FNH_YMDHM CHAR(12),
	TH16_POW_TRWI_QTY NUMBER(9,0),
	FRAM_DTM DATE,
	MDFY_DTM DATE NOT NULL,
	TH0_POW_STRT_YMD CHAR(8),
	TH0_POW_FNH_YMD CHAR(8),
	PRDN_QTY2 NUMBER(9,0),
	TH0_POW_TRWI_QTY NUMBER(9,0),
	PRDN_QTY3 NUMBER(9,0),
	PRDN_PLNT_CD VARCHAR(3) NOT NULL,
	CONSTRAINT TB_PLNT_PROD_MST_SUM_INFO_PK PRIMARY KEY (APL_YMD,DATA_SN,PRDN_PLNT_CD)
);
CREATE UNIQUE INDEX TB_PLNT_PROD_MST_SUM_INFO_IDX1 ON TB_PLNT_PROD_MST_SUM_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,APL_YMD,PRDN_PLNT_CD);


-- KOMMS_ADM.TB_PLNT_VEHL_MGMT definition

-- Drop table

-- DROP TABLE TB_PLNT_VEHL_MGMT;

CREATE TABLE TB_PLNT_VEHL_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) NOT NULL,
	SORT_SN NUMBER(3,0) NOT NULL,
	PLNT_NM VARCHAR(50),
	CONSTRAINT TB_PLNT_VEHL_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_PRDN_ORD_NO_EXCEL definition

-- Drop table

-- DROP TABLE TB_PRDN_ORD_NO_EXCEL;

CREATE TABLE TB_PRDN_ORD_NO_EXCEL (
	PRDN_ORD_NO VARCHAR(15) NOT NULL,
	BASC_MDL_CD VARCHAR(12),
	DEST_NAT_CD VARCHAR(5),
	ORD_QTY NUMBER(15,0),
	PRDN_QTY NUMBER(9,0),
	PRDN_PLN_QTY NUMBER(9,0)
);


-- KOMMS_ADM.TB_PRDN_ORD_NO_TEMP definition

-- Drop table

-- DROP TABLE TB_PRDN_ORD_NO_TEMP;

CREATE TABLE TB_PRDN_ORD_NO_TEMP (
	PRDN_ORD_NO VARCHAR(15) NOT NULL,
	BASC_MDL_CD VARCHAR(12),
	DEST_NAT_CD VARCHAR(5),
	ORD_QTY NUMBER(15,0),
	PRDN_QTY NUMBER(9,0),
	PRDN_PLN_QTY NUMBER(9,0),
	DYTM_PLN_NAT_CD CHAR(5) NOT NULL,
	CONSTRAINT TB_PRDN_ORD_NO_TEMP_PK PRIMARY KEY (PRDN_ORD_NO,DYTM_PLN_NAT_CD)
);


-- KOMMS_ADM.TB_PRNT_ALGN_INFO definition

-- Drop table

-- DROP TABLE TB_PRNT_ALGN_INFO;

CREATE TABLE TB_PRNT_ALGN_INFO (
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	DEPPC1_SN NUMBER(5,0) NOT NULL,
	DL_EXPD_PRNT_PG_SN NUMBER(5,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	PRNT_INSD_PG_SBC VARCHAR(100),
	DEPPR1_YN CHAR(1),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	LRNK_CD VARCHAR(4) NOT NULL,
	CONSTRAINT TB_PRNT_ALGN_INFO_PK PRIMARY KEY (N_PRNT_PBCN_NO,LRNK_CD,DEPPC1_SN,DL_EXPD_PRNT_PG_SN)
);
CREATE INDEX TB_PRNT_ALGN_INFO_IDX1 ON TB_PRNT_ALGN_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO);


-- KOMMS_ADM.TB_PRNT_BKGD_INFO definition

-- Drop table

-- DROP TABLE TB_PRNT_BKGD_INFO;

CREATE TABLE TB_PRNT_BKGD_INFO (
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	OLD_PRNT_PBCN_NO VARCHAR(100),
	CRE_YMD CHAR(8) NOT NULL,
	DL_EXPD_RDCS_ST_CD VARCHAR(4) NOT NULL,
	TRTM_YMD CHAR(8) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	PRTL_SBC VARCHAR(4000),
	CONSTRAINT TB_PRNT_BKGD_INFO_PK PRIMARY KEY (N_PRNT_PBCN_NO)
);
CREATE UNIQUE INDEX TB_PRNT_BKGD_INFO_IDX1 ON TB_PRNT_BKGD_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO);


-- KOMMS_ADM.TB_PRNT_FP_INFO definition

-- Drop table

-- DROP TABLE TB_PRNT_FP_INFO;

CREATE TABLE TB_PRNT_FP_INFO (
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DLVG_PARR_YMD CHAR(8) NOT NULL,
	DL_EXPD_DLVG_PL_CD VARCHAR(4),
	OLD_PRNT_PBCN_NO VARCHAR(100),
	I_WAY_SBC VARCHAR(100),
	BKBD_WAY_SBC VARCHAR(100),
	PG_MGN_SBC VARCHAR(100),
	DEPCQ1_SBC VARCHAR(100),
	DEIPQ1_SBC VARCHAR(100),
	PRNT_CVR_SBC VARCHAR(100),
	PRNT_INSD_PG_SBC VARCHAR(100),
	C_PRNT_CVR_SBC VARCHAR(100),
	C_PRNT_INSD_PG_SBC VARCHAR(100),
	CVR_CEG_SBC VARCHAR(100),
	PG_NL NUMBER(5,0),
	CVR_NL NUMBER(5,0),
	EXPD_NL NUMBER(5,0),
	GRN_DOC_NL NUMBER(5,0),
	POST_CRD_NL NUMBER(5,0),
	EOFU1_NL NUMBER(5,0),
	NR_FLM_MKO_NL NUMBER(5,0),
	DGTL_PRNT_NL NUMBER(5,0),
	OORD_EDIT_PG_NL NUMBER(5,0),
	DEPC1_QTY NUMBER(5,0),
	REM VARCHAR(100),
	IV_QTY NUMBER(9,0),
	ORD_QTY NUMBER(15,0),
	MO_AVG_PRDN_QTY NUMBER(9,0),
	RQ_QTY NUMBER(5,0) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_PRNT_FP_INFO_PK PRIMARY KEY (N_PRNT_PBCN_NO)
);
CREATE UNIQUE INDEX TB_PRNT_FP_INFO_IDX1 ON TB_PRNT_FP_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO);


-- KOMMS_ADM.TB_PRNT_PAGE_MGMT definition

-- Drop table

-- DROP TABLE TB_PRNT_PAGE_MGMT;

CREATE TABLE TB_PRNT_PAGE_MGMT (
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	DEPPC1_SN NUMBER(5,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	RGST_YMD CHAR(8) NOT NULL,
	END_PG_SN NUMBER(5,0) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	LRNK_CD VARCHAR(4) NOT NULL,
	CONSTRAINT TB_PRNT_PAGE_MGMT_PK PRIMARY KEY (N_PRNT_PBCN_NO,LRNK_CD,DEPPC1_SN)
);
CREATE INDEX TB_PRNT_PAGE_MGMT_IDX1 ON TB_PRNT_PAGE_MGMT (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD);


-- KOMMS_ADM.TB_PRNT_REQ_INFO definition

-- Drop table

-- DROP TABLE TB_PRNT_REQ_INFO;

CREATE TABLE TB_PRNT_REQ_INFO (
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	PRNT_PARR_YMD CHAR(8) NOT NULL,
	DLVG_PARR_YMD CHAR(8) NOT NULL,
	I_WAY_CD VARCHAR(4),
	PRNT_PARR_QTY NUMBER(9,0) NOT NULL,
	PRNT_WAY_CD VARCHAR(4),
	DEPQ1_CD VARCHAR(4),
	OLD_PRNT_PBCN_NO VARCHAR(100),
	PG_MGN_SBC VARCHAR(100),
	PG_NL NUMBER(5,0),
	OORD_EDIT_PG_NL NUMBER(5,0),
	GRN_DOC_NL NUMBER(5,0),
	MDFY_PG_NL NUMBER(5,0),
	DEPC1_YN CHAR(1),
	PRTL_IMTR_SBC VARCHAR(4000),
	SALE_UNP NUMBER(15,2),
	ORDN_RQST_YMD CHAR(8) NOT NULL,
	ORDN_CSET_CDT CHAR(8),
	N1AFP2_ADR VARCHAR(200),
	N2AFP2_ADR VARCHAR(200),
	CRGR_EENO VARCHAR(20) NOT NULL,
	CSET_CRGR_EENO VARCHAR(20),
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	PRTL_IMTR_SBC2 VARCHAR(4000),
	PRNT_WAY_CD2 VARCHAR(15),
	PRNT_PARR_BGT NUMBER(15,2),
	PRTL_IMTR_SBC3 VARCHAR(20),
	ATTC_YN VARCHAR(1),
	CONSTRAINT TB_PRNT_REQ_INFO_PK PRIMARY KEY (N_PRNT_PBCN_NO)
);
CREATE UNIQUE INDEX TB_PRNT_REQ_INFO_IDX1 ON TB_PRNT_REQ_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO);


-- KOMMS_ADM.TB_PROD_MST_INFO definition

-- Drop table

-- DROP TABLE TB_PROD_MST_INFO;

CREATE TABLE TB_PROD_MST_INFO (
	PRDN_MST_VEHL_CD VARCHAR(4) NOT NULL,
	BN_SN CHAR(6) NOT NULL,
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	APL_YMD CHAR(8) NOT NULL,
	USF_CD VARCHAR(2) NOT NULL,
	MO_PACK_CD VARCHAR(4) NOT NULL,
	PRDN_ORD_NO VARCHAR(15) NOT NULL,
	PRDN_MST_NAT_CD VARCHAR(5) NOT NULL,
	BASC_MDL_CD VARCHAR(12),
	PRDN_OCN_CD VARCHAR(4),
	VER_CD VARCHAR(3),
	DEST_NAT_CD VARCHAR(5) NOT NULL,
	POW_LOC_CD VARCHAR(2) NOT NULL,
	TH1_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH2_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH3_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH4_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH5_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH6_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH7_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH8_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH9_POW_STRT_YMDHM CHAR(12) NOT NULL,
	T10PS1_YMDHM CHAR(12) NOT NULL,
	T11PS1_YMDHM CHAR(12) NOT NULL,
	T12PS1_YMDHM CHAR(12) NOT NULL,
	T13PS1_YMDHM CHAR(12) NOT NULL,
	T14PS1_YMDHM CHAR(12) NOT NULL,
	T15PS1_YMDHM CHAR(12) NOT NULL,
	T16PS1_YMDHM CHAR(12) NOT NULL,
	MDL_MDY_CD VARCHAR(2),
	VIN CHAR(17) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	MDFY_DTM DATE NOT NULL,
	TH0_POW_STRT_YMD CHAR(8),
	TRWI_YMD CHAR(8) NOT NULL,
	TRWI_USED_YN CHAR(1),
	PRDN_POW_LOC_CD VARCHAR(2),
	PRDN_MDL_MDY_CD VARCHAR(2),
	QLTY_VEHL_CD VARCHAR(4),
	DL_EXPD_NAT_CD VARCHAR(5),
	TH1_POW_STRT_YMD CHAR(8),
	TH2_POW_STRT_YMD CHAR(8),
	TH3_POW_STRT_YMD CHAR(8),
	TH4_POW_STRT_YMD CHAR(8),
	TH5_POW_STRT_YMD CHAR(8),
	TH6_POW_STRT_YMD CHAR(8),
	TH7_POW_STRT_YMD CHAR(8),
	TH8_POW_STRT_YMD CHAR(8),
	TH9_POW_STRT_YMD CHAR(8),
	T10PS1_YMD CHAR(8),
	T11PS1_YMD CHAR(8),
	T12PS1_YMD CHAR(8),
	T13PS1_YMD CHAR(8),
	T14PS1_YMD CHAR(8),
	T15PS1_YMD CHAR(8),
	T16PS1_YMD CHAR(8),
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N',
	CONSTRAINT TB_PROD_MST_INFO_PK PRIMARY KEY (PRDN_MST_VEHL_CD,BN_SN,DL_EXPD_CO_CD,APL_YMD,VIN)
);
CREATE INDEX TB_PROD_MST_INFO_IDX1 ON TB_PROD_MST_INFO (APL_YMD,DL_EXPD_CO_CD);
CREATE INDEX TB_PROD_MST_INFO_IDX2 ON TB_PROD_MST_INFO (TRWI_YMD,DL_EXPD_CO_CD,PRDN_MST_VEHL_CD);
CREATE INDEX TB_PROD_MST_INFO_IDX3 ON TB_PROD_MST_INFO (VIN,DL_EXPD_CO_CD);


-- KOMMS_ADM.TB_PROD_MST_INFO_ERP_KMC definition

-- Drop table

-- DROP TABLE TB_PROD_MST_INFO_ERP_KMC;

CREATE TABLE TB_PROD_MST_INFO_ERP_KMC (
	PRDN_MST_VEHL_CD CHAR(4) NOT NULL,
	BN_SN CHAR(6) NOT NULL,
	APL_YMD CHAR(8) NOT NULL,
	USF_CD CHAR(1),
	MO_PACK_CD CHAR(4),
	PRDN_ORD_NO CHAR(9),
	PRDN_MST_NAT_CD CHAR(5),
	BASC_MDL_CD CHAR(12),
	PRDN_OCN_CD CHAR(4),
	VER_CD CHAR(3),
	DEST_NAT_CD CHAR(5),
	POW_LOC_CD CHAR(4),
	TH1_POW_STRT_YMDHM CHAR(12),
	TH2_POW_STRT_YMDHM CHAR(12),
	TH3_POW_STRT_YMDHM CHAR(12),
	TH4_POW_STRT_YMDHM CHAR(12),
	TH5_POW_STRT_YMDHM CHAR(12),
	TH6_POW_STRT_YMDHM CHAR(12),
	TH7_POW_STRT_YMDHM CHAR(12),
	TH8_POW_STRT_YMDHM CHAR(12),
	TH9_POW_STRT_YMDHM CHAR(12),
	T10PS1_YMDHM CHAR(12),
	T11PS1_YMDHM CHAR(12),
	MDL_MDY_CD CHAR(2),
	VIN CHAR(17),
	PLNT_CD CHAR(4),
	RCPM_TRTM_YN CHAR(1),
	TRTM_YMD CHAR(8),
	TH1_POW_STRT_YMD CHAR(8),
	TH2_POW_STRT_YMD CHAR(8),
	TH3_POW_STRT_YMD CHAR(8),
	TH4_POW_STRT_YMD CHAR(8),
	TH5_POW_STRT_YMD CHAR(8),
	TH6_POW_STRT_YMD CHAR(8),
	TH7_POW_STRT_YMD CHAR(8),
	TH8_POW_STRT_YMD CHAR(8),
	TH9_POW_STRT_YMD CHAR(8),
	T10PS1_YMD CHAR(8),
	T11PS1_YMD CHAR(8),
	ET_GUBN_CD CHAR(2)
);
CREATE INDEX TB_PROD_MST_INFO_ERP_KMC_01 ON TB_PROD_MST_INFO_ERP_KMC (APL_YMD,USF_CD,PRDN_MST_VEHL_CD,BN_SN);
CREATE INDEX TB_PROD_MST_INFO_ERP_KMC_02 ON TB_PROD_MST_INFO_ERP_KMC (APL_YMD);
CREATE INDEX TB_PROD_MST_INFO_ERP_KMC_VIN ON TB_PROD_MST_INFO_ERP_KMC (VIN);


-- KOMMS_ADM.TB_PROD_MST_NOAPIM_INFO definition

-- Drop table

-- DROP TABLE TB_PROD_MST_NOAPIM_INFO;

CREATE TABLE TB_PROD_MST_NOAPIM_INFO (
	APL_YMD CHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(4) NOT NULL,
	PRDN_MST_NAT_CD VARCHAR(5) NOT NULL,
	PRDN_TRWI_QTY NUMBER(9,0) NOT NULL,
	PRDN_QTY NUMBER(9,0) NOT NULL,
	FRAM_DTM DATE,
	MDFY_DTM DATE NOT NULL,
	PRDN_QTY2 NUMBER(9,0),
	PRDN_QTY3 NUMBER(9,0),
	CONSTRAINT TB_PROD_MST_NOAPIM_INFO_PK PRIMARY KEY (APL_YMD,QLTY_VEHL_CD,MDL_MDY_CD,PRDN_MST_NAT_CD)
);


-- KOMMS_ADM.TB_PROD_MST_PROG_INFO definition

-- Drop table

-- DROP TABLE TB_PROD_MST_PROG_INFO;

CREATE TABLE TB_PROD_MST_PROG_INFO (
	PRDN_MST_VEHL_CD VARCHAR(4) NOT NULL,
	BN_SN CHAR(6) NOT NULL,
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	APL_STRT_YMD CHAR(8) NOT NULL,
	APL_FNH_YMD CHAR(8) NOT NULL,
	USF_CD VARCHAR(2) NOT NULL,
	MO_PACK_CD VARCHAR(4) NOT NULL,
	DEST_NAT_CD VARCHAR(5) NOT NULL,
	POW_LOC_CD VARCHAR(2) NOT NULL,
	TH1_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH2_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH3_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH4_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH5_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH6_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH7_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH8_POW_STRT_YMDHM CHAR(12) NOT NULL,
	TH9_POW_STRT_YMDHM CHAR(12) NOT NULL,
	T10PS1_YMDHM CHAR(12) NOT NULL,
	T11PS1_YMDHM CHAR(12) NOT NULL,
	T12PS1_YMDHM CHAR(12) NOT NULL,
	T13PS1_YMDHM CHAR(12) NOT NULL,
	T14PS1_YMDHM CHAR(12) NOT NULL,
	T15PS1_YMDHM CHAR(12) NOT NULL,
	T16PS1_YMDHM CHAR(12) NOT NULL,
	MDL_MDY_CD VARCHAR(2),
	VIN CHAR(17) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	MDFY_DTM DATE NOT NULL,
	TH0_POW_STRT_YMD CHAR(8),
	PRDN_MDL_MDY_CD VARCHAR(2),
	QLTY_VEHL_CD VARCHAR(4),
	DL_EXPD_NAT_CD VARCHAR(5),
	TRWI_USED_YN CHAR(1),
	DTL_SN NUMBER(11,0) NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	CONSTRAINT TB_PROD_MST_PROG_INFO_PK PRIMARY KEY (PRDN_MST_VEHL_CD,BN_SN,DL_EXPD_CO_CD,APL_STRT_YMD,APL_FNH_YMD,DTL_SN,VIN)
);
CREATE INDEX TB_PROD_MST_PROG_INFO_IDX1 ON TB_PROD_MST_PROG_INFO (APL_STRT_YMD,APL_FNH_YMD,DL_EXPD_CO_CD);
CREATE INDEX TB_PROD_MST_PROG_INFO_IDX2 ON TB_PROD_MST_PROG_INFO (VIN,DL_EXPD_CO_CD);


-- KOMMS_ADM.TB_PROD_MST_SUM_INFO definition

-- Drop table

-- DROP TABLE TB_PROD_MST_SUM_INFO;

CREATE TABLE TB_PROD_MST_SUM_INFO (
	APL_YMD CHAR(8) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	PRDN_TRWI_QTY NUMBER(9,0) NOT NULL,
	PRDN_QTY NUMBER(9,0) NOT NULL,
	TH1_POW_STRT_YMDHM CHAR(12),
	TH1_POW_FNH_YMDHM CHAR(12),
	TH1_POW_TRWI_QTY NUMBER(9,0),
	TH2_POW_STRT_YMDHM CHAR(12),
	TH2_POW_FNH_YMDHM CHAR(12),
	TH2_POW_TRWI_QTY NUMBER(9,0),
	TH3_POW_STRT_YMDHM CHAR(12),
	TH3_POW_FNH_YMDHM CHAR(12),
	TH3_POW_TRWI_QTY NUMBER(9,0),
	TH4_POW_STRT_YMDHM CHAR(12),
	TH4_POW_FNH_YMDHM CHAR(12),
	TH4_POW_TRWI_QTY NUMBER(9,0),
	TH5_POW_STRT_YMDHM CHAR(12),
	TH5_POW_FNH_YMDHM CHAR(12),
	TH5_POW_TRWI_QTY NUMBER(9,0),
	TH6_POW_STRT_YMDHM CHAR(12),
	TH6_POW_FNH_YMDHM CHAR(12),
	TH6_POW_TRWI_QTY NUMBER(9,0),
	TH7_POW_STRT_YMDHM CHAR(12),
	TH7_POW_FNH_YMDHM CHAR(12),
	TH7_POW_TRWI_QTY NUMBER(9,0),
	TH8_POW_STRT_YMDHM CHAR(12),
	TH8_POW_FNH_YMDHM CHAR(12),
	TH8_POW_TRWI_QTY NUMBER(9,0),
	TH9_POW_STRT_YMDHM CHAR(12),
	TH9_POW_FNH_YMDHM CHAR(12),
	TH9_POW_TRWI_QTY NUMBER(9,0),
	T10PS1_YMDHM CHAR(12),
	TH10_POW_FNH_YMDHM CHAR(12),
	TH10_POW_TRWI_QTY NUMBER(9,0),
	T11PS1_YMDHM CHAR(12),
	TH11_POW_FNH_YMDHM CHAR(12),
	TH11_POW_TRWI_QTY NUMBER(9,0),
	T12PS1_YMDHM CHAR(12),
	TH12_POW_FNH_YMDHM CHAR(12),
	TH12_POW_TRWI_QTY NUMBER(9,0),
	T13PS1_YMDHM CHAR(12),
	TH13_POW_FNH_YMDHM CHAR(12),
	TH13_POW_TRWI_QTY NUMBER(9,0),
	T14PS1_YMDHM CHAR(12),
	TH14_POW_FNH_YMDHM CHAR(12),
	TH14_POW_TRWI_QTY NUMBER(9,0),
	T15PS1_YMDHM CHAR(12),
	TH15_POW_FNH_YMDHM CHAR(12),
	TH15_POW_TRWI_QTY NUMBER(9,0),
	T16PS1_YMDHM CHAR(12),
	TH16_POW_FNH_YMDHM CHAR(12),
	TH16_POW_TRWI_QTY NUMBER(9,0),
	FRAM_DTM DATE,
	MDFY_DTM DATE NOT NULL,
	TH0_POW_STRT_YMD CHAR(8),
	TH0_POW_FNH_YMD CHAR(8),
	PRDN_QTY2 NUMBER(9,0),
	TH0_POW_TRWI_QTY NUMBER(9,0),
	PRDN_QTY3 NUMBER(9,0),
	CONSTRAINT TB_PROD_MST_SUM_INFO_PK PRIMARY KEY (APL_YMD,DATA_SN)
);
CREATE UNIQUE INDEX TB_PROD_MST_SUM_INFO_IDX1 ON TB_PROD_MST_SUM_INFO (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,APL_YMD);


-- KOMMS_ADM.TB_PROD_MST_TRWI_INFO definition

-- Drop table

-- DROP TABLE TB_PROD_MST_TRWI_INFO;

CREATE TABLE TB_PROD_MST_TRWI_INFO (
	PRDN_MST_VEHL_CD VARCHAR(4) NOT NULL,
	BN_SN CHAR(6) NOT NULL,
	DL_EXPD_CO_CD VARCHAR(4) NOT NULL,
	APL_YMD CHAR(8) NOT NULL,
	TRWI_YMD CHAR(8) NOT NULL,
	USF_CD VARCHAR(2) NOT NULL,
	MO_PACK_CD VARCHAR(4) NOT NULL,
	DEST_NAT_CD VARCHAR(5) NOT NULL,
	POW_LOC_CD VARCHAR(2) NOT NULL,
	MDL_MDY_CD VARCHAR(2),
	VIN CHAR(17) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	MDFY_DTM DATE NOT NULL,
	PRDN_MDL_MDY_CD VARCHAR(2),
	QLTY_VEHL_CD VARCHAR(4),
	DL_EXPD_NAT_CD VARCHAR(5),
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N',
	CONSTRAINT TB_PROD_MST_TRWI_INFO_PK PRIMARY KEY (PRDN_MST_VEHL_CD,BN_SN,DL_EXPD_CO_CD,APL_YMD,VIN)
);
CREATE INDEX TB_PROD_MST_TRWI_INFO_IDX1 ON TB_PROD_MST_TRWI_INFO (APL_YMD,DL_EXPD_CO_CD);
CREATE INDEX TB_PROD_MST_TRWI_INFO_IDX2 ON TB_PROD_MST_TRWI_INFO (TRWI_YMD,DL_EXPD_CO_CD,PRDN_MST_VEHL_CD);
CREATE INDEX TB_PROD_MST_TRWI_INFO_IDX3 ON TB_PROD_MST_TRWI_INFO (VIN,DL_EXPD_CO_CD);


-- KOMMS_ADM.TB_PROD_ODR_INFO definition

-- Drop table

-- DROP TABLE TB_PROD_ODR_INFO;

CREATE TABLE TB_PROD_ODR_INFO (
	MO_PACK_CD VARCHAR(4) NOT NULL,
	DATA_SN NUMBER(7,0) NOT NULL,
	APL_YMD VARCHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	PRDN_TRWI_QTY NUMBER(9,0) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	MDFY_DTM DATE NOT NULL,
	PRDN_PLNT_CD VARCHAR(1) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_PROD_ODR_INFO PRIMARY KEY (MO_PACK_CD,DATA_SN,APL_YMD,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_SEWHA_DIVS_INFO definition

-- Drop table

-- DROP TABLE TB_SEWHA_DIVS_INFO;

CREATE TABLE TB_SEWHA_DIVS_INFO (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	WHOT_YMD CHAR(8) NOT NULL,
	DL_EXPD_RQ_SCN_CD VARCHAR(4) NOT NULL,
	RQ_QTY NUMBER(5,0) NOT NULL,
	DIVS_QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DIVS_DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	DIVS_LANG_CD VARCHAR(3) NOT NULL,
	PRTL_IMTR_SBC VARCHAR(4000),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_SEWHA_DIVS_INFO_PK PRIMARY KEY (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,DL_EXPD_MDL_MDY_CD,N_PRNT_PBCN_NO,WHOT_YMD,DL_EXPD_RQ_SCN_CD)
);
CREATE INDEX TB_SEWHA_DIVS_INFO_IDX1 ON TB_SEWHA_DIVS_INFO (WHOT_YMD,QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD);


-- KOMMS_ADM.TB_SEWHA_IV_INFO definition

-- Drop table

-- DROP TABLE TB_SEWHA_IV_INFO;

CREATE TABLE TB_SEWHA_IV_INFO (
	CLS_YMD CHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	IV_QTY NUMBER(9,0) NOT NULL,
	DL_EXPD_TMP_IV_QTY NUMBER(9,0),
	CMPL_YN CHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	TMP_TRTM_YN CHAR(1),
	DEEI1_QTY NUMBER(9,0),
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_SEWHA_IV_INFO PRIMARY KEY (CLS_YMD,QLTY_VEHL_CD,DL_EXPD_MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_SEWHA_IV_INFO_DTL definition

-- Drop table

-- DROP TABLE TB_SEWHA_IV_INFO_DTL;

CREATE TABLE TB_SEWHA_IV_INFO_DTL (
	CLS_YMD CHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	IV_QTY NUMBER(9,0) NOT NULL,
	SFTY_IV_QTY NUMBER(9,0) NOT NULL,
	DL_EXPD_TMP_IV_QTY NUMBER(9,0),
	CMPL_YN CHAR(1),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	TMP_TRTM_YN CHAR(1),
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_SEWHA_IV_INFO_DTL PRIMARY KEY (CLS_YMD,QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD,DL_EXPD_MDL_MDY_CD,N_PRNT_PBCN_NO,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_SEWHA_WHOT_INFO definition

-- Drop table

-- DROP TABLE TB_SEWHA_WHOT_INFO;

CREATE TABLE TB_SEWHA_WHOT_INFO (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	DTL_SN NUMBER(11,0) NOT NULL,
	WHOT_YMD CHAR(8) NOT NULL,
	DL_EXPD_RQ_SCN_CD VARCHAR(4) NOT NULL,
	DLVG_PARR_YMD CHAR(8),
	DLVG_PARR_HHMM CHAR(4),
	RQ_QTY NUMBER(5,0) NOT NULL,
	PWTI_EENO VARCHAR(20),
	PRTL_IMTR_SBC VARCHAR(4000),
	CRGR_EENO VARCHAR(20),
	DL_EXPD_BOX_QTY NUMBER(9,0),
	CMPL_YN CHAR(1),
	WHSN_YMD CHAR(8),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	DEL_YN CHAR(1),
	PWTI_NM VARCHAR(20),
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	DL_EXPD_WHOT_ST_CD VARCHAR(4) DEFAULT '01',
	CONSTRAINT PK_TB_SEWHA_WHOT_INFO PRIMARY KEY (QLTY_VEHL_CD,DL_EXPD_MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO,DTL_SN,MDL_MDY_CD,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_SEWHA_WHSN_INFO definition

-- Drop table

-- DROP TABLE TB_SEWHA_WHSN_INFO;

CREATE TABLE TB_SEWHA_WHSN_INFO (
	WHSN_YMD CHAR(8) NOT NULL,
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DL_EXPD_MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	N_PRNT_PBCN_NO VARCHAR(100) NOT NULL,
	WHSN_QTY NUMBER(9,0) NOT NULL,
	CRGR_EENO VARCHAR(20) NOT NULL,
	PRNT_PARR_YMD CHAR(8) NOT NULL,
	DLVG_PARR_YMD CHAR(8) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	PRDN_PLNT_CD VARCHAR(3) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_TB_SEWHA_WHSN_INFO PRIMARY KEY (WHSN_YMD,QLTY_VEHL_CD,DL_EXPD_MDL_MDY_CD,LANG_CD,N_PRNT_PBCN_NO,MDL_MDY_CD,PRDN_PLNT_CD)
);


-- KOMMS_ADM.TB_SFTY_IV_MGMT definition

-- Drop table

-- DROP TABLE TB_SFTY_IV_MGMT;

CREATE TABLE TB_SFTY_IV_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	LANG_CD VARCHAR(3) NOT NULL,
	MO_AVG_ORD_QTY NUMBER(9,0),
	MAPP1_QTY NUMBER(9,0),
	MO_AVG_PRDN_QTY NUMBER(9,0),
	TSID141_QTY NUMBER(9,0),
	TSID31_QTY NUMBER(9,0),
	DSID141_QTY NUMBER(9,0),
	DSID31_QTY NUMBER(9,0),
	USE_YN CHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_SFTY_IV_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,MDL_MDY_CD,LANG_CD)
);


-- KOMMS_ADM.TB_TEMP_LANG_MGMT definition

-- Drop table

-- DROP TABLE TB_TEMP_LANG_MGMT;

CREATE TABLE TB_TEMP_LANG_MGMT (
	LANG_CD VARCHAR(3) NOT NULL,
	LANG_CD_NM VARCHAR(200) NOT NULL,
	USE_YN VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT PK_TB_TEMP_LANG_MGMT PRIMARY KEY (LANG_CD)
);


-- KOMMS_ADM.TB_TEST_VEHL definition

-- Drop table

-- DROP TABLE TB_TEST_VEHL;

CREATE TABLE TB_TEST_VEHL (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	QLTY_VEHL_NM VARCHAR(100),
	USE_YN VARCHAR(1),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE
);


-- KOMMS_ADM.TB_USR_MGMT definition

-- Drop table

-- DROP TABLE TB_USR_MGMT;

CREATE TABLE TB_USR_MGMT (
	USER_EENO VARCHAR(20) NOT NULL,
	USER_PW VARCHAR(256) NOT NULL,
	USER_NM VARCHAR(50) NOT NULL,
	BLNS_CO_CD VARCHAR(4) NOT NULL,
	USER_DCD VARCHAR(8) NOT NULL,
	USER_EML_ADR VARCHAR(100),
	USE_YN VARCHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	PW_ALTR_DTM DATE DEFAULT SYSDATE NOT NULL,
	FIN_LGI_DTM DATE DEFAULT SYSDATE NOT NULL,
	PW_LOCK_DTM DATE,
	PW_ERR_OFT NUMBER DEFAULT 0 NOT NULL,
	USER_CHG_PW VARCHAR(1) DEFAULT '0' NOT NULL,
	GRP_CD VARCHAR(3),
	USER_OSET_LGI VARCHAR(1),
	USE_GBN VARCHAR(1) DEFAULT 'U' NOT NULL,
	CONSTRAINT TB_USR_MGMT_PK PRIMARY KEY (USER_EENO)
);


-- KOMMS_ADM.TB_USR_MGMT_EXCEL definition

-- Drop table

-- DROP TABLE TB_USR_MGMT_EXCEL;

CREATE TABLE TB_USR_MGMT_EXCEL (
	USER_EENO VARCHAR(20),
	USER_PW VARCHAR(10),
	USER_NM VARCHAR(20),
	BLNS_CO_NM VARCHAR(100),
	USER_OPS_NM VARCHAR(100),
	USER_EML_ADR VARCHAR(100),
	USER_TN VARCHAR(14),
	USER_HP_NO CHAR(14),
	USE_YN CHAR(1),
	PGM01_IQ_VEHL VARCHAR(4000),
	PGM01_INP_VEHL VARCHAR(4000),
	PGM02_IQ_VEHL VARCHAR(4000),
	PGM02_INP_VEHL VARCHAR(4000),
	PGM03_IQ_VEHL VARCHAR(4000),
	PGM03_INP_VEHL VARCHAR(4000),
	PGM04_IQ_VEHL VARCHAR(4000),
	PGM04_INP_VEHL VARCHAR(4000),
	PGM05_IQ_VEHL VARCHAR(4000),
	PGM05_INP_VEHL VARCHAR(4000),
	PGM06_IQ_VEHL VARCHAR(4000),
	PGM06_INP_VEHL VARCHAR(4000),
	PGM07_IQ_VEHL VARCHAR(4000),
	PGM07_INP_VEHL VARCHAR(4000),
	PGM08_IQ_VEHL VARCHAR(4000),
	PGM08_INP_VEHL VARCHAR(4000),
	PGM09_IQ_VEHL VARCHAR(4000),
	PGM09_INP_VEHL VARCHAR(4000),
	PGM10_IQ_VEHL VARCHAR(4000),
	PGM10_INP_VEHL VARCHAR(4000),
	PGM11_IQ_VEHL VARCHAR(4000),
	PGM11_INP_VEHL VARCHAR(4000),
	PGM12_IQ_VEHL VARCHAR(4000),
	PGM12_INP_VEHL VARCHAR(4000),
	PGM13_IQ_VEHL VARCHAR(4000),
	PGM13_INP_VEHL VARCHAR(4000),
	PGM14_IQ_VEHL VARCHAR(4000),
	PGM14_INP_VEHL VARCHAR(4000),
	PGM15_IQ_VEHL VARCHAR(4000),
	PGM15_INP_VEHL VARCHAR(4000),
	PGM16_IQ_VEHL VARCHAR(4000),
	PGM16_INP_VEHL VARCHAR(4000),
	PGM17_IQ_VEHL VARCHAR(4000),
	PGM17_INP_VEHL VARCHAR(4000),
	PGM18_IQ_VEHL VARCHAR(4000),
	PGM18_INP_VEHL VARCHAR(4000),
	PGM19_IQ_VEHL VARCHAR(4000),
	PGM19_INP_VEHL VARCHAR(4000),
	PGM20_IQ_VEHL VARCHAR(4000),
	PGM20_INP_VEHL VARCHAR(4000),
	PGM21_IQ_VEHL VARCHAR(4000),
	PGM21_INP_VEHL VARCHAR(4000),
	PGM22_IQ_VEHL VARCHAR(4000),
	PGM22_INP_VEHL VARCHAR(4000),
	PGM23_IQ_VEHL VARCHAR(4000),
	PGM23_INP_VEHL VARCHAR(4000),
	PGM24_IQ_VEHL VARCHAR(4000),
	PGM24_INP_VEHL VARCHAR(4000),
	PGM25_IQ_VEHL VARCHAR(4000),
	PGM25_INP_VEHL VARCHAR(4000),
	PGM26_IQ_VEHL VARCHAR(4000),
	PGM26_INP_VEHL VARCHAR(4000),
	PGM27_IQ_VEHL VARCHAR(4000),
	PGM27_INP_VEHL VARCHAR(4000),
	PGM28_IQ_VEHL VARCHAR(4000),
	PGM28_INP_VEHL VARCHAR(4000),
	PGM29_IQ_VEHL VARCHAR(4000),
	PGM29_INP_VEHL VARCHAR(4000),
	PGM30_IQ_VEHL VARCHAR(4000),
	PGM30_INP_VEHL VARCHAR(4000)
);


-- KOMMS_ADM.TB_VEHL_CRGR_MGMT definition

-- Drop table

-- DROP TABLE TB_VEHL_CRGR_MGMT;

CREATE TABLE TB_VEHL_CRGR_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	CRGR_EENO VARCHAR(20) NOT NULL,
	BLNS_CO_CD VARCHAR(4) NOT NULL,
	USE_YN CHAR(1) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	ET_YN CHAR(1),
	CONSTRAINT TB_VEHL_CRGR_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,MDL_MDY_CD,CRGR_EENO)
);


-- KOMMS_ADM.TB_VEHL_MDY_MGMT definition

-- Drop table

-- DROP TABLE TB_VEHL_MDY_MGMT;

CREATE TABLE TB_VEHL_MDY_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4) NOT NULL,
	DESMP1_CD VARCHAR(4) NOT NULL,
	DEFMP1_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_VEHL_MDY_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,DL_EXPD_REGN_CD,DESMP1_CD)
);


-- KOMMS_ADM.TB_VEHL_MDY_REL_MGMT definition

-- Drop table

-- DROP TABLE TB_VEHL_MDY_REL_MGMT;

CREATE TABLE TB_VEHL_MDY_REL_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	DL_EXPD_REGN_CD VARCHAR(4) NOT NULL,
	JB_MDY_REL_CD VARCHAR(4) NOT NULL,
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	CONSTRAINT TB_VEHL_MDY_REL_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,MDL_MDY_CD,DL_EXPD_REGN_CD)
);


-- KOMMS_ADM.TB_VEHL_MGMT definition

-- Drop table

-- DROP TABLE TB_VEHL_MGMT;

CREATE TABLE TB_VEHL_MGMT (
	QLTY_VEHL_CD VARCHAR(4) NOT NULL,
	MDL_MDY_CD VARCHAR(2) NOT NULL,
	DL_EXPD_CO_CD VARCHAR(4),
	QLTY_VEHL_NM VARCHAR(100),
	DL_EXPD_PAC_SCN_CD VARCHAR(4),
	DL_EXPD_PDI_CD VARCHAR(4),
	JB_MDY_REL_CD VARCHAR(4),
	DYTM_PLN_VEHL_CD VARCHAR(4),
	PRDN_MST_VEHL_CD VARCHAR(4),
	BOM_VEHL_CD VARCHAR(4),
	USE_YN VARCHAR(1),
	PPRR_EENO VARCHAR(20) NOT NULL,
	FRAM_DTM DATE NOT NULL,
	UPDR_EENO VARCHAR(20),
	MDFY_DTM DATE,
	ET_YN VARCHAR(1),
	CONSTRAINT TB_VEHL_MGMT_PK PRIMARY KEY (QLTY_VEHL_CD,MDL_MDY_CD)
);
CREATE INDEX TB_VEHL_MGMT_IDX1 ON TB_VEHL_MGMT (MDL_MDY_CD,DL_EXPD_CO_CD,DL_EXPD_PAC_SCN_CD,DL_EXPD_PDI_CD);


-- KOMMS_ADM.TB_VIN definition

-- Drop table

-- DROP TABLE TB_VIN;

CREATE TABLE TB_VIN (
	PRDN_MST_VEHL_CD VARCHAR(4) NOT NULL,
	BN_SN CHAR(6) NOT NULL,
	VIN CHAR(17),
	PDI_IN DATE,
	PDI_IN_YMD VARCHAR(8)
);


-- KOMMS_ADM.TB_VIN_NOEXIST definition

-- Drop table

-- DROP TABLE TB_VIN_NOEXIST;

CREATE TABLE TB_VIN_NOEXIST (
	PRDN_MST_VEHL_CD VARCHAR(4) NOT NULL,
	BN_SN CHAR(6) NOT NULL,
	VIN CHAR(17),
	PDI_IN DATE
);


-- KOMMS_ADM.TB_WRK_DATE_MGMT definition

-- Drop table

-- DROP TABLE TB_WRK_DATE_MGMT;

CREATE TABLE TB_WRK_DATE_MGMT (
	WK_YMD CHAR(8) NOT NULL,
	DOW_CD CHAR(1) NOT NULL,
	HOLI_YN CHAR(1) NOT NULL,
	CONSTRAINT TB_WRK_DATE_MGMT_PK PRIMARY KEY (WK_YMD)
);